### ISSUE TITLE
Question(vue): why is `@typescript-eslint/no-unused-vars` for `*.vue` `off`

### ISSUE THREAD

**Issue by OrbisK** [antfu/eslint-config#103]
https://github.com/antfu/eslint-config/blob/master/packages/vue/index.js#L12

Why is `@typescript-eslint/no-unused-vars` `off` for `*.vue` files?

Just asking 😏

**Comment by antfu** [comment]
Coz I always use TypeScript which already handles that.

**Comment by OrbisK** [comment]
okay, thanks. 👍
