### ISSUE TITLE
"eslint": ">=7.4.0" as peer dependency is not proper version

### ISSUE THREAD

**Issue by yunsii** [antfu/eslint-config#104]
### Describe the bug

When I use `eslint@7.32.0`, I got error: 

```
Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Failed to load plugin 'unicorn' declared in '.eslintrc » @antfu/eslint-config » @antfu/eslint-config-vue » @antfu/eslint-config-ts » @antfu/eslint-config-basic': Cannot find module 'eslint/use-at-your-own-risk'
```

related issue: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1544#issuecomment-1097321596

### Reproduction

https://github.com/yunsii/antfu-eslint-config

### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 14.13 GB / 19.55 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Any reason you can use eslint 8?

**Comment by yunsii** [comment]
I copy the peer dependency to install eslint 😂 and encounter the error, No reason can't use eslint 8.
