### ISSUE TITLE
Peer dependency warning: TypeScript

### ISSUE THREAD

**Issue by Demir-Utku** [antfu/eslint-config#105]
### Describe the bug

I used `@antfu/eslint-config` package in my Vue 3 project that I don't use TypeScript. When I installed the package, I got a peer dependency warning. It told me that I should install TypeScript as a dev dependency, which I don't want to do (for now).

### Reproduction

Create a new Vue 3 project (possibly with Vite) without TypeScript. Then, install `@antfu/eslint-config` package (with pnpm). When installing the dependency, you'll receive a peer dependency warning related to TypeScript.

### System Info

```Shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 114.16 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    pnpm: 7.8.0 - ~/Library/pnpm/pnpm
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
Browsers:
    Firefox Developer Edition: 104.0
    Safari: 15.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This preset is supposed to work with TypeScript. If you don't want it, try https://github.com/antfu/eslint-config/tree/main/packages/basic
