### ISSUE TITLE
fix auto error 

### ISSUE THREAD

**Issue by dbudaiya** [antfu/eslint-config#108]
### Describe the bug

The plug -in is introduced and used, the vscode file is automatically fixed, and the file is saved after the file is modified

### Reproduction

https://github.com/dbudaiya/dushenyan-utils

### System Info

```Shell
ESLint: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json » @antfu/eslint-config » @antfu/eslint-config-react » @antfu/eslint-config-ts': ENOENT: no such file or directory, open '/Users/dushenyan/Documents/openSource-code/dushenyan-utils/node_modules/.pnpm/@typescript-eslint+eslint-plugin@5.33.1_3bh5nkk7utn7e74vrwtv6rxmt4/node_modules/@typescript-eslint/eslint-plugin/dist/index.js' Referenced from: /Users/dushenyan/Documents/openSource-code/dushenyan-utils/node_modules/@antfu/eslint-config-ts/index.js. Please see the 'ESLint' output channel for details.
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Remove `node_modules` and reinstall.
