### ISSUE TITLE
Vue linting rules without TS

### ISSUE THREAD

**Issue by jd-solanki** [antfu/eslint-config#109]
### Clear and concise description of the problem

Is it possible for you to provide, linting rules for vue without TS rules?

### Suggested solution

It requires removing 3-4 lines from the existing `index.js` file and related packages from `package.json`

### Alternative

None

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sorry I have no bandwidth nor interest in this. Since this preset is a bit operated for myself, I'd suggest you fork it and maintain your own version.
