### ISSUE TITLE
Enable `@typescript-eslint/no-floating-promises` and `@typescript-eslint/no-misused-promises`

### ISSUE THREAD

**Issue by ZanMinKian** [antfu/eslint-config#112]
### Clear and concise description of the problem

It make sense to enable rules [no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises/) and [no-misused-promises](https://typescript-eslint.io/rules/no-misused-promises/). They can warn you not forget to `await` the async function. What why not enable them?

### Suggested solution

Enable `@typescript-eslint/no-floating-promises` and `@typescript-eslint/no-misused-promises`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
If it handles `.then` and `.catch` well I think we could have it
