### ISSUE TITLE
no-undef is not work

### ISSUE THREAD

**Issue by Valar103769** [antfu/eslint-config#115]
### Describe the bug

<img width="651" alt="image" src="https://user-images.githubusercontent.com/36926073/189090396-5cdd468f-012b-4c73-a6d0-833e6245091b.png">

  please add rule: `no-undef': 'error'`, otherwise, cause push bug to product, like as `console.log(sadadadaxzad)`

### Reproduction

https://www.jianshu.com/p/627d8b2aaa4a

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 912.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 105.0.5195.102
    Safari: 15.6.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's intentional as TypeScript already checks it.

**Comment by Valar103769** [comment]
> 

but if not `<script lang='ts'>` ?

**Comment by antfu** [comment]
This preset is designed to work with TypeScript. Feel free to enable it locally if you want to.
