### ISSUE TITLE
Protect against leaving `.only` in your tests

### ISSUE THREAD

**Issue by JessicaSachs** [antfu/eslint-config#121]
### Clear and concise description of the problem

Sometimes when I write Vitest, Jest, Mocha, or Cypress tests, I commit `.only` describe or it blocks that I forgot about while developing.

This is bad because CI passes, but my test suites aren't running.

### Suggested solution

Can we either extend or include something like https://www.npmjs.com/package/eslint-plugin-no-only-tests

### Alternative

Projects do it themselves.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sounds great. Open to PRs :)
