### ISSUE TITLE
基于 @antfu 二次封装 Shareable 库，提示 Error: Failed to load plugin 'import' declared in 'clean-webpack-plugin/.eslintrc.cjs » @shilong/eslint-config/lib/base.js » @antfu/eslint-config-basic': Cannot find module 'eslint-plugin-import'

### ISSUE THREAD

**Issue by Onlylonger** [antfu/eslint-config#122]
### Describe the bug

基于 @antfu 二次封装 Shareable 库，提示 Error: 
Failed to load plugin 'import' declared in 'clean-webpack-plugin/.eslintrc.cjs » @shilong/eslint-config/lib/base.js » @antfu/eslint-config-basic': Cannot find module 'eslint-plugin-import'.

应该不是bug. 但是希望求助下大神如何解决这类问题；

### Reproduction

https://github.com/Onlylonger/eslint/tree/new

### System Info

```Shell
在 clean-webpack-plugin 目录里面。
npx eslint .
```

### Used Package Manager

npm

### Validations

- [ ] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [ ] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ColinLQ** [comment]
在 vscode 中遇到了同样的问题
