### ISSUE TITLE
The indentation line looks weird

### ISSUE THREAD

**Issue by Locter9001** [antfu/eslint-config#126]
### Describe the bug

![image](https://user-images.githubusercontent.com/96331179/198867088-c1b065a3-9575-4a7e-be3d-7d4a682e573f.png)

I set 4 spaces as an indent, but his indent line didn't follow, I'm not sure what triggered this

### Reproduction

module.exports = {     extends: '@antfu',     rules: {         '@typescript-eslint/no-use-before-define': 'off',         '@typescript-eslint/prefer-ts-expect-error': 'off',         '@typescript-eslint/ban-ts-comment': 'off',         'no-console': 'off',         'vue/html-indent': ['error', 4],         '@typescript-eslint/semi': ['error', 'always'],         '@typescript-eslint/indent': ['error', 4],         'indent': ['error', 4],         'semi': ['error', 'always'],         'prefer-promise-reject-errors': 'off',         'no-debugger': 'warn',         'no-restricted-syntax': 'off',         '@typescript-eslint/brace-style': ['error', '1tbs'],     }, };

### System Info

```Shell
System:
    OS: Windows 10
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 16.40 GB / 31.34 GB
  Binaries:
    Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - f:\SDK_ALL\Yarn\bin\yarn.CMD
    npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.22621.601.0
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Locter9001** [comment]
This doesn't look like a bug, but I couldn't find a discussion forum so I had to post it here

**Comment by ntnyq** [comment]
Have you changed your editor config indent to 4 spaces?

**Comment by Locter9001** [comment]
```JavaScript
module.exports = {
    extends: '@antfu',
    rules: {
        '@typescript-eslint/no-use-before-define': 'off',
        '@typescript-eslint/prefer-ts-expect-error': 'off',
        '@typescript-eslint/ban-ts-comment': 'off',
        'no-console': 'off',
        'curly': [2, 'all'],
        'vue/html-indent': ['error', 4],
        '@typescript-eslint/semi': ['error', 'always'],
        '@typescript-eslint/indent': ['error', 4],
        'indent': ['error', 4, { SwitchCase: 1 }],
        'semi': ['error', 'always'],
        'prefer-promise-reject-errors': 'off',
        'no-debugger': 'warn',
        'no-restricted-syntax': 'off',
        '@typescript-eslint/brace-style': ['error', '1tbs'],
    },
};
```

**Comment by ntnyq** [comment]
> ```js
> module.exports = {
>     extends: '@antfu',
>     rules: {
>         '@typescript-eslint/no-use-before-define': 'off',
>         '@typescript-eslint/prefer-ts-expect-error': 'off',
>         '@typescript-eslint/ban-ts-comment': 'off',
>         'no-console': 'off',
>         'curly': [2, 'all'],
>         'vue/html-indent': ['error', 4],
>         '@typescript-eslint/semi': ['error', 'always'],
>         '@typescript-eslint/indent': ['error', 4],
>         'indent': ['error', 4, { SwitchCase: 1 }],
>         'semi': ['error', 'always'],
>         'prefer-promise-reject-errors': 'off',
>         'no-debugger': 'warn',
>         'no-restricted-syntax': 'off',
>         '@typescript-eslint/brace-style': ['error', '1tbs'],
>     },
> };
> ```

The indent line behavior has nothing to do with your ESLint config but your editor config.

代码缩进和你的 ESLint 配置没有关系，而是和你的编辑器配置有关。

Besides, you should disable rule `indent` in favor of rule `@typescript-eslint/indent` and other rules included both in `eslint` and `@typescript-eslint`.

另外，你应该禁用规则 `indent` 以支持规则 `@typescript-eslint/indent`。类似地，还有其他同时存在于 `eslint` 和 `@typescript-eslint` 的规则。

**Comment by Locter9001** [comment]
> > ```js
> > module.exports = {
> >     extends: '@antfu',
> >     rules: {
> >         '@typescript-eslint/no-use-before-define': 'off',
> >         '@typescript-eslint/prefer-ts-expect-error': 'off',
> >         '@typescript-eslint/ban-ts-comment': 'off',
> >         'no-console': 'off',
> >         'curly': [2, 'all'],
> >         'vue/html-indent': ['error', 4],
> >         '@typescript-eslint/semi': ['error', 'always'],
> >         '@typescript-eslint/indent': ['error', 4],
> >         'indent': ['error', 4, { SwitchCase: 1 }],
> >         'semi': ['error', 'always'],
> >         'prefer-promise-reject-errors': 'off',
> >         'no-debugger': 'warn',
> >         'no-restricted-syntax': 'off',
> >         '@typescript-eslint/brace-style': ['error', '1tbs'],
> >     },
> > };
> > ```
> 
> The indent line behavior has nothing to do with your ESLint config but your editor config.
> 
> 编辑器缩进线和你的 ESLint 配置没有关系，而是和你的编辑器配置有关。
> 
> Besides, you should disable rule `indent` in favor of rule `@typescript-eslint/indent` and other rules included both in `eslint` and `@typescript-eslint`.
> 
> 另外，你应该禁用规则 `indent` 以支持规则 `@typescript-eslint/indent`。类似地，还有其他同时存在于 `eslint` 和 `@typescript-eslint` 的规则。

okay thanks 🫡🫡
