### ISSUE TITLE
fix： Unnecessary { after 'if' condition.

### ISSUE THREAD

**Issue by dxhuii** [antfu/eslint-config#130]
### Describe the bug

![image](https://user-images.githubusercontent.com/2328917/202896622-ed3bde35-0100-49d2-b491-da12ca1b325c.png)

auto format

```ts
// 月
    if (now.getFullYear() === old.getFullYear() && now.getMonth() === old.getMonth()) {
      h[month]++
    }
    else
      h[month] = 1

    // 周
    const weekStart = dayjs().startOf('week').valueOf()
    const weekEnd = dayjs().endOf('week').valueOf()
    if (last >= weekStart && last <= weekEnd) {
      h[week]++
    }
    else
      h[week] = 1

    // 日
    if (now.getFullYear() === old.getFullYear() && now.getMonth() === old.getMonth() && now.getDate() === old.getDate()) {
      h[day]++
    }
    else
      h[day] = 1
```

modify to:

```ts
// 月
    if (now.getFullYear() === old.getFullYear() && now.getMonth() === old.getMonth())
      h[month]++
    else h[month] = 1

    // 周
    const weekStart = dayjs().startOf('week').valueOf()
    const weekEnd = dayjs().endOf('week').valueOf()
    if (last >= weekStart && last <= weekEnd)
      h[week]++
    else h[week] = 1

    // 日
    if (now.getFullYear() === old.getFullYear() && now.getMonth() === old.getMonth() && now.getDate() === old.getDate())
      h[day]++
    else h[day] = 1
```
no warning

### Reproduction

无

### System Info

```Shell
System:
    OS: macOS 12.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 394.57 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 16.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kirklin** [comment]
Maybe this is curly rule has something to do with it, I have modified the curly rule, which seems to be bug-free in my place
[@kirklin/eslint-config](https://github.com/kirklin/eslint-config)

**Comment by antfu** [comment]
It's my preference. You can just override it in your local config.

**Comment by kirklin** [comment]
好像问题不是风格喜好的事情，而是if内的条件非常多的时候，将if语句后跟大括号的代码格式化成if语句后后面没大括号的时候会出问题。
