### ISSUE TITLE
Add type hints to the configuration

### ISSUE THREAD

**Issue by nooooooom** [antfu/eslint-config#148]
### Clear and concise description of the problem

`@antfu/eslint-config` has become a part of my daily development specification customization reference, and I like some of its customized coding specifications!

This may be a little different. When I want to delve into the rules or principles of a library, I always like downloading its source code and reviewing it in the editor. But when I open the source code of this library to know the details of a specific rule, I always need to open the corresponding website and search for the corresponding rule name. It's a hassle for people who want to know what these rules disable/enable! I tried to find out if I could add hints to eslint config, so I found [`eslint-define-config`](https://github.com/Shinigami92/eslint-define-config), which has `@antfu/eslint-config` uses most of the prompt information and the corresponding link address in the external configuration, so can we also add it.

There should be some people who have the same needs as me, because eslint is a plug-in for code style, which varies from person to person. We always want to learn something from others to notice have yet to catch. Add type hints to this to make this even more convenient!

### Suggested solution

Add type hints to the configuration, e.g. [`eslint-define-config`](https://github.com/Shinigami92/eslint-define-config).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
#250 should addressed it
