### ISSUE TITLE
Add JSON-related configuration in the README file

### ISSUE THREAD

**Issue by joaopalmeiro** [antfu/eslint-config#153]
Hi! 👋 

In order to automatically format `json` and `jsonc` files, I had to add them to the [`eslint.validate` option](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) in the `settings.json` file (in addition to the other options). So, if you find it relevant, I think this setting could also be added in the README file, more precisely in the `Config VS Code auto fix` section as a link to [this page](https://ota-meshi.github.io/eslint-plugin-jsonc/user-guide/#visual-studio-code) or based on the snippet below:

```jsonc
{
  "eslint.validate": ["javascript", "javascriptreact", "json", "jsonc"]
}
```

What do you think? If it makes sense, let me know if I can help! 😄 

**References**:

- https://ota-meshi.github.io/eslint-plugin-jsonc/user-guide/#visual-studio-code
- https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
- https://code.visualstudio.com/docs/languages/identifiers

**Comment by antfu** [comment]
I'd love to have this, but the problem I faced is that it will overkill on projects with other eslint configs (without json/jsonc parser). Not sure if there is a way to fix this.

**Comment by joaopalmeiro** [comment]
Thanks for the feedback, @antfu!

I'm not sure if I'm seeing the problem the way you are, sorry. With your configuration, there is support for JSON ([configuration](https://github.com/antfu/eslint-config/blob/main/packages/basic/index.js#L49) and [parser](https://github.com/antfu/eslint-config/blob/main/packages/basic/package.json#L34)). This suggestion was more for this to be leveraged by VS Code as well, as is the case with other parts. Is there any part that I am interpreting incorrectly? Maybe just put it as a suggestion and not as part of the default setup for VS Code?

**Comment by antfu** [comment]
It would be better to have them in the workspace setting (.vscode/settings.json) instead of user's global settings. We could document it with the mentioning.

**Comment by joaopalmeiro** [comment]
Sorry, I wasn't considering user/global vs. workspace settings. I was always thinking just about workspace settings. 

I agree with you. Maybe [this README section](https://github.com/antfu/eslint-config#config-vs-code-auto-fix) could be a bit more explicitly mentioning it's workspace/project configuration and add this suggestion like you said?

**Comment by antfu** [comment]
Sure, looking forward to the PR :)

**Comment by JenieX** [comment]
I came searching the issues after noticing that `.json` and `.md` files are not being linted as stated. After looking to it, I think it just isn't that important to add more packages. I'm switching my projects to `ts` from `js`, and the difference in size on the disk is just too much already. 😄
