### ISSUE TITLE
 Cannot find module 'eslint-plugin-vue'

### ISSUE THREAD

**Issue by lalahuang** [antfu/eslint-config#154]
### 格式化vue文件的时候就会报错

![image](https://user-images.githubusercontent.com/17737354/216513297-1862f869-0599-452b-ae30-4d41c5dd3941.png)

packages.json
![image](https://user-images.githubusercontent.com/17737354/216513348-91a6c7f2-06cd-4b4c-80b2-b90854808c1a.png)
.eslintrc.js
![image](https://user-images.githubusercontent.com/17737354/216513391-9001e719-bc99-469b-9eef-8b29d01577ad.png)

,vscode.settings.json 工作区
![image](https://user-images.githubusercontent.com/17737354/216513479-cfe90e56-7394-4e1a-ad64-90fadcb03a55.png)

### Reproduction

- https://github.com/lalahuang/vueeslinttest

### System Info

```Shell
-
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lalahuang** [comment]
而且我发现在vscode中，直接保存会失效，运行eslint --fix 就可以执行。不清楚问题出在哪里了

**Comment by lalahuang** [comment]
改用npm 重新安装依赖后可以了。但是我想用pnpm。。。 @antfu 救救救！

**Comment by Aicmortal** [comment]
me too

**Comment by Aicmortal** [comment]
@lalahuang 
你可以在.npmrc文件中添加以下配置暂时解决问题:
```
shamefully-hoist=true
strict-peer-dependencies=false
```
