### ISSUE TITLE
no-unused-imports is not compatible with `vue template`

### ISSUE THREAD

**Issue by alexzhang1030** [antfu/eslint-config#155]
### Describe the bug

When I'm reference `type` only in `template`, `no-unused-imports` will report an error. I believe this is an upstream issue, so I'm going to try to fix this issue.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-svdpb2?file=src%2FApp.vue&terminal=lint

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 267.08 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 107.0
    Safari: 16.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by so1ve** [comment]
The latest eslint-plugin-vue has fixed this problem. You can send a pr to upgrade it

**Comment by alexzhang1030** [comment]
I just bumped to the latest version, and this issue has been fixed, well done!
