### ISSUE TITLE
how to change to use Tabs?

### ISSUE THREAD

**Issue by billbravo99** [antfu/eslint-config#156]
### Describe the bug

how to change to use Tabs?

### Reproduction

how to change to use Tabs?

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 111.77 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.15 - /opt/homebrew/opt/node@16/bin/yarn
    npm: 8.11.0 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Brave Browser: 109.1.47.186
    Firefox Developer Edition: 109.0
    Safari: 16.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by n1j0** [comment]
@billbravo99, hope I can help you a little bit after my first look into @antfu 's set of applied eslint rules.

The rules for spacing can be found in this file https://github.com/antfu/eslint-config/blob/main/packages/basic/standard.js.

There are two rules you need to change / override in your .eslintrc:

1. "indent" is currently:
`'indent': ['error', 2, { SwitchCase: 1, VariableDeclarator: 1, outerIIFEBody: 1, MemberExpression: 1, FunctionDeclaration: { parameters: 1, body: 1 }, FunctionExpression: { parameters: 1, body: 1 }, CallExpression: { arguments: 1 }, ArrayExpression: 1, ObjectExpression: 1, ImportDeclaration: 1, flatTernaryExpressions: false, ignoreComments: false, ignoredNodes: ['TemplateLiteral *', 'JSXElement', 'JSXElement > *', 'JSXAttribute', 'JSXIdentifier', 'JSXNamespacedName', 'JSXMemberExpression', 'JSXSpreadAttribute', 'JSXExpressionContainer', 'JSXOpeningElement', 'JSXClosingElement', 'JSXFragment', 'JSXOpeningFragment', 'JSXClosingFragment', 'JSXText', 'JSXEmptyExpression', 'JSXSpreadChild'], offsetTernaryExpressions: true, }],`

2. "no-tabs" is currently:
`'no-tabs': 'error',`

Your current ".eslintrc" might look like this (if you not already added some overrides or customisations):

`{ "extends": "@antfu" }`

So if you really just want to replace spaces with tabs and everything else should stay the same, your ".eslintrc" should look like this:

`{
"extends": "@antfu",
"rules": { "no-tabs": 0 }
"indent": ["error", "tab", { SwitchCase: 1, VariableDeclarator: 1, outerIIFEBody: 1, MemberExpression: 1, FunctionDeclaration: { parameters: 1, body: 1 }, FunctionExpression: { parameters: 1, body: 1 }, CallExpression: { arguments: 1 }, ArrayExpression: 1, ObjectExpression: 1, ImportDeclaration: 1, flatTernaryExpressions: false, ignoreComments: false, ignoredNodes: ["TemplateLiteral *", "JSXElement", "JSXElement > *", "JSXAttribute", "JSXIdentifier", "JSXNamespacedName", "JSXMemberExpression", "JSXSpreadAttribute", "JSXExpressionContainer", "JSXOpeningElement", "JSXClosingElement", "JSXFragment", "JSXOpeningFragment", "JSXClosingFragment", "JSXText", "JSXEmptyExpression", "JSXSpreadChild"], offsetTernaryExpressions: true, }],
}`

Sorry for the bad format and ironically no indentation 😀

**Comment by antfu** [comment]
Thanks @n1j0!
