### ISSUE TITLE
Syntax Error: Error: Failed to load config "plugin:vue/vue3-recommended" to extend from.

### ISSUE THREAD

**Issue by varnew** [antfu/eslint-config#170]
### Describe the bug

when i add the package into a vue2 project, it throw an error: “Syntax Error: Error: Failed to load config "plugin:vue/vue3-recommended" to extend from. ”
how can i do for it ？

### Reproduction

add the package into a vue2 project

### System Info

```Shell
"vue": "^2.6.11"
"@antfu/eslint-config": "^0.35.3"
"eslint": "^6.7.2"
node v16.14.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This config has no intention to support Vue 2. You might fork it to fit your need
