### ISSUE TITLE
Configuration for rule "import/newline-after-import" is invalid

### ISSUE THREAD

**Issue by Jamiewarb** [antfu/eslint-config#175]
### Describe the bug

Just upgraded to latest version, receiving the following:

ESLint: 8.38.0

```
Error: .eslintrc.json » @hexdigital/eslint-config » @antfu/eslint-config » @antfu/eslint-config-vue » @antfu/eslint-config-ts » @antfu/eslint-config-basic:
	Configuration for rule "import/newline-after-import" is invalid:
	Value {"count":1,"considerComments":true} should NOT have additional properties.
```

eslint config is:

```
{
  "extends": "@antfu"
}
```

### Reproduction

https://stackblitz.com/edit/typescript-tqfes4?file=eslint.json

### System Info

```Shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 119.31 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.8.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 112.0.5615.121
    Firefox: 103.0.1
    Firefox Developer Edition: 100.0
    Safari: 15.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Jamiewarb** [comment]
Removing the `"considerComments": true` flag solves the error.

However, from the docs, your configuration looks valid: https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/newline-after-import.md

So it may be an issue further upstream. I wonder if we can remove `considerComments` right now until this is resolved so that this dependency will continue to work

**Comment by zanminkian** [comment]
The link https://stackblitz.com/edit/typescript-tqfes4?file=eslint.json you provided doesn't seems reproduce.

**Comment by Jamiewarb** [comment]
Looks like it may now have been fixed upstream
