### ISSUE TITLE
Strict Mode

### ISSUE THREAD

**Issue by zanminkian** [antfu/eslint-config#183]
### Clear and concise description of the problem

Detecting `tsconfig.eslint.json` file (in the project root) or configuring `ESLINT_TSCONFIG` env is not clear way to use `TypeScript Aware Rules`.

### Suggested solution

Step 1. Do not detect `tsconfig.eslint.json` file and remove supporting `ESLINT_TSCONFIG` env.
Step 2. Support `ESLINT_STRICT` env. If user run `ESLINT_STRICT=true eslint .`, enable the buit-in `typescript aware rules` (and other rules if they built in).
Step 3. Update README. Tell user how to enable strict mode.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zanminkian** [comment]
If it makes sense, I'm glad to create a PR to implement it.

**Comment by antfu** [comment]
I am not very sure. The reason we were doing that it trying to find a middle ground, where you can do that without much configuration, while the majority of users won't be affected by this. If have a env in your command it's acceptable to you, isn't `ESLINT_TSCONFIG=tsconfig.json eslint .` also working as you expected?

**Comment by zanminkian** [comment]
Both are ok. But `ESLINT_STRICT` is much more ergonomic and easy-understanding, in my humble opinion. Moreover, we can add more rules which do not belongs to `typescript aware rules`  to enhance the Strict Mode.

**Comment by zanminkian** [comment]
For example, setting [consistent-type-assertions](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-assertions.md) to `never` and enabling [no-explicit-any](https://typescript-eslint.io/rules/no-explicit-any/) to block assertions and any declaration to make project type safer. They should work under `STRICT` mode, but they are not Typescript aware rules.

**Comment by antfu** [comment]
With the flat config it should be much easier to support this. As I don't have much need on this myself, I'll close is for now. If you still want to push it, feel free to bring it back. Thanks.
