### ISSUE TITLE
how to format .js/ts/json files without prettier

### ISSUE THREAD

**Issue by Mr-Nobody-li** [antfu/eslint-config#197]
### Describe the bug

how to format .js/ts/json files without prettier?

### Reproduction

If needed, it will be provided

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10505 CPU @ 3.20GHz
    Memory: 4.66 GB / 15.72 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.37), ChromiumDev (115.0.1880.3)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
`eslint . --fix`

**Comment by kathirr007** [comment]
@antfu I've added **settings.json** in project level **.vscode/settings.json** with suggested configuration. But auto-formatting is not working while saving. It's working when I run script **eslint . --fix**, but not auto-formatting while saving.

Following is my files structure:

![image](https://github.com/antfu/eslint-config/assets/13422232/2fd68eed-f816-4472-84e0-c42ce423dc42)

Any suggestion to get auto-formatting would be appreciated.

**Comment by kathirr007** [comment]
It's not working when there are multiple folders at the root level. It's working fine with a single root folder. 
Can we make it work with multiple root folders?
