### ISSUE TITLE
drop eslint-plugin-import

### ISSUE THREAD

**Issue by arily** [antfu/eslint-config#203]
### Clear and concise description of the problem

Hi,
I am running into an issue with TS5.0 extends.

My tsconfig.json
```json
{
  "extends": ["./.nuxt/tsconfig.json", "./tsconfig.base.json"]
}
```
will cause an error:
```
Oops! Something went wrong! :(

ESLint: 8.43.0

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
Occurred while linting /repo/nuxt.config.ts:2
Rule: "import/default"
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:1172:7)
    at loadTsconfig (/repo/node_modules/tsconfig-paths/lib/tsconfig-loader.js:93:39)
    at loadSyncDefault (/repo/node_modules/tsconfig-paths/lib/tsconfig-loader.js:40:18)
    at tsConfigLoader (/repo/node_modules/tsconfig-paths/lib/tsconfig-loader.js:26:22)
    at readTsConfig (/repo/node_modules/eslint-plugin-import/lib/ExportMap.js:818:528)
    at isEsModuleInterop (/repo/node_modules/eslint-plugin-import/lib/ExportMap.js:821:277)
    at ExportMap.parse (/repo/node_modules/eslint-plugin-import/lib/ExportMap.js:808:317)
    at ExportMap.for (/repo/node_modules/eslint-plugin-import/lib/ExportMap.js:807:201)
```
related issues/prs: 
- https://github.com/import-js/eslint-plugin-import/issues/2751
- https://github.com/import-js/eslint-plugin-import/pull/2447
in short: Maintainers of `eslint-plugin-import` decided to prioritize support node 4 over Typescript 5

### Suggested solution

[switch to `eslint-plugin-i`](https://github.com/import-js/eslint-plugin-import/issues/2751#issuecomment-1519091123)

### Alternative

here are some hacks mentioned in the related issues:
- https://github.com/import-js/eslint-plugin-import/issues/2751#issuecomment-1496216195
- https://github.com/import-js/eslint-plugin-import/issues/2751#issuecomment-1499270368
- https://github.com/import-js/eslint-plugin-import/pull/2447#issuecomment-1542663986

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by arily** [comment]
https://github.com/antfu/eslint-config/pull/205

here you go

**Comment by baixiaoyu2997** [comment]
Just a reminder for users who want to switch to multiple values for `extends`. Although the related pull request has resolved this issue, you may still encounter the "TypeError: value.replace is not a function" error when using `@commitlint`. Please refer to: https://github.com/TypeStrong/ts-node/issues/2000#issuecomment-1519339593 for more information.

**Comment by fxzer** [comment]
![image](https://github.com/antfu/eslint-config/assets/68853957/166e677b-e03b-446b-9f71-d75b073466b9)
我遇到了相同的问题，请问怎么解决呢？
I have encountered the same problem, how can I solve it?
