### ISSUE TITLE
.eslintrc error | Configuration for rule "import/newline-after-import" is invalid: should NOT have additional properties.

### ISSUE THREAD

**Issue by hey-david-perez** [antfu/eslint-config#207]
### Describe the bug

This error is happening inside Webstorm with default template using: https://github.com/antfu/vitesse-nuxt3

```
Error: .eslintrc » @antfu/eslint-config » @antfu/eslint-config-vue » @antfu/eslint-config-ts » @antfu/eslint-config-basic:
	Configuration for rule "import/newline-after-import" is invalid:
	Value {"count":1,"considerComments":true} should NOT have additional properties.
```

### Reproduction

https://github.com/antfu/vitesse-nuxt3

### System Info

```Shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 114.98 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    pnpm: 8.6.5 - ~/Work/Repos/portal-client/level4/node_modules/.bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kirklin** [comment]
Hi,

I was unable to reproduce the problem you mentioned. I tested the default template using the link you provided (https://github.com/antfu/vitesse-nuxt3) in Webstorm, but I did not encounter the reported error.

To help resolve this issue, I suggest trying the following steps:

Upgrade your Webstorm version to the latest available release. Sometimes, updating the IDE can resolve compatibility issues with certain configurations.
Regarding the current Webstorm version you are using, could you please provide me with that information? It will help me better understand the context of the problem you are facing.
