### ISSUE TITLE
vue2 没有 ts 能用这个预设吗？

### ISSUE THREAD

**Issue by jaycethanks** [antfu/eslint-config#208]
### Clear and concise description of the problem

我的项目是vue2， 在尝试用这个预设， 但是在解析 vue 文件时，会报错 ` Parsing error: Cannot find module 'typescript`
但是我有看到 `@antfu/eslint-config-vue/index.js`  这个文件中有去判断 是否 有用ts的逻辑， 是 有考虑 兼容吗？
为什么 不论有没有 ts, 都是用 `vue-eslint-parser` 去解析 vue 文件呢？
```js
    {
      files: ['*.vue'],
      parser: 'vue-eslint-parser',
      parserOptions: {
        parser: '@typescript-eslint/parser',
      },
      rules: {
        'no-unused-vars': 'off',
        'no-undef': 'off',
        ...(TS
          ? { '@typescript-eslint/no-unused-vars': 'off' }
          : null),
      },
    },
```

### Suggested solution

- help -

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
不是特别有兴趣花时间在支持 vue2 或 非typescript 上，建议你可以自己修，或是用别的预设
