### ISSUE TITLE
Ban declaration in ts file

### ISSUE THREAD

**Issue by zanminkian** [antfu/eslint-config#216]
### Clear and concise description of the problem

```ts
// xxx.ts
declare class Person {
  name: string
}
const p = new Person()
```

Code above will cause error. `declare` statement should exist in `.d.ts` file and should not exist in `.ts` file. Banning declaration in ts file is good for managing the code base.

### Suggested solution

User should use `declare` in `.d.ts` only, not `.ts`. Adding a rule `antfu/no-decalare-in-ts` can help.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Yeah I am fine having it :)
