### ISSUE TITLE
After upgrading to 0.39.8 eslint fails on suggested .eslintrc.js

### ISSUE THREAD

**Issue by some-user123** [antfu/eslint-config#222]
### Describe the bug

I'm using the suggested config from the README:
```js
// .eslintrc.js
process.env.ESLINT_TSCONFIG = 'tsconfig.json'

module.exports = {
  extends: '@antfu'
}
```

That won't pass eslint check after upgrade to 0.39.8:

```
Error:   1:1  error  Unexpected use of the global variable 'process'. Use 'require("process")' instead  n/prefer-global/process
```

Seems inconsistent to me 😉

### Reproduction

https://github.com/antfu/eslint-config/

### System Info

```Shell
Binaries:
    Node: 18.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.2 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.82)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Tragio** [comment]
This is due to https://github.com/antfu/eslint-config/pull/214.

You can exclude that rule in `.eslintrc.js` using the following:

```js
// .eslintrc.js
process.env.ESLINT_TSCONFIG = 'tsconfig.json'

module.exports = {
  extends: '@antfu',
  rules: { 'n/prefer-global/process': 0 },
}
```

**Comment by some-user123** [comment]
I know, that I can just disable the rule. However, I'd expect to find a guide in the Readme that doesn't violate its own rules or requires changing them...
