### ISSUE TITLE
`Parsing error` in .md file

### ISSUE THREAD

**Issue by liby** [antfu/eslint-config#228]
### Describe the bug

Write the following code in the Markdown file, encountered an ESLint error: "Parsing error: ';' expected".
```
   parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    project: ['./tsconfig.json', './tsconfig.node.json'],
    tsconfigRootDir: __dirname,
   },
```

<img width="916" alt="image" src="https://github.com/antfu/eslint-config/assets/38807139/b82d7080-0693-4b9c-8c0a-ad3c034a8aa9">

Possible related issues: https://github.com/antfu/eslint-config/issues/128

### Reproduction

https://github.com/liby/antfu-eslint-config-issue

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 31.25 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/n/bin/node
    npm: 8.19.4 - ~/n/bin/npm
    pnpm: 8.6.9 - ~/n/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.248
    Safari: 16.5.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's just because the code snippet is not a valid JS. You can add `<!-- eslint-skip -->` before the code block to bypass it.
