### ISSUE TITLE
eslint plugin error tips not work in vscode

### ISSUE THREAD

**Issue by ckvv** [antfu/eslint-config#231]
### Describe the bug

when . add `.npmrc` file, eslint plugin error tips not work in vscode

```
public-hoist-pattern[]=@vue/runtime-core
```

### Reproduction

https://github.com/ckvv/vue-eslint

### System Info

```Shell
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 36.93 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 9.6.4 - ~/Library/pnpm/npm
  Browsers:
    Chrome: 115.0.5790.114
    Firefox: 113.0.2
    Safari: 15.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This is not related to eslint, but more like a general pnpm caveat. It's out of our scope to document it. Thanks for bringing this up.
