### ISSUE TITLE
After installing antfu/eslint-config, do I need to install the typescript-eslint vue-eslint

### ISSUE THREAD

**Issue by laterdayi** [antfu/eslint-config#236]
### Describe the bug

I think the documentation is missing some instructions. Do I need to install other plugins after installing antfu/eslint-config?

```
 "@typescript-eslint/eslint-plugin": "^6.5.0",
 "@typescript-eslint/parser": "^6.5.0",
"@vue/eslint-config-prettier": "^8.0.0",
"@vue/eslint-config-typescript": "^11.0.3",
"eslint": "8.48.0",
"eslint-plugin-standard-recommended": "^1.2.1",
"eslint-plugin-vue": "^9.17.0",
  "@rushstack/eslint-patch": "^1.3.3"
```

1. Are these plug-ins no longer needed?
2. If I want to use other extensions, how should I configure them
3. How do I configure overlay rules if I want to use them

Look forward to help

### Reproduction

*

### System Info

```Shell
windows
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by so1ve** [comment]
No, pnpm will hoist eslint-related dependnecies automatically so you don't have to install them by your self

**Comment by laterdayi** [comment]
@so1ve   Thanks to your help, doesn't even the basic eslint need to be installed?

**Comment by laterdayi** [comment]
1. If I want to use other extensions, how should I configure them
2. How do I configure overlay rules if I want to use them

How should these two types be implemented? Is there any similar demo or configuration

**Comment by so1ve** [comment]
You have to install the `eslint` package

```js
// .eslintrc.js
module.exports = {
  extends: "@antfu",
  rules: {/* ... */},
};
```

**Comment by laterdayi** [comment]
To ensure proper use, I just need to install `eslint`,

```
 "@typescript-eslint/eslint-plugin": "^6.5.0",
 "@typescript-eslint/parser": "^6.5.0",
"@vue/eslint-config-prettier": "^8.0.0",
"@vue/eslint-config-typescript": "^11.0.3",
"eslint-plugin-standard-recommended": "^1.2.1",
"eslint-plugin-vue": "^9.17.0",
"@rushstack/eslint-patch": "^1.3.3"
```
Is no installation required?

**Comment by so1ve** [comment]
Yes. You just need to install `eslint` and `@antfu/eslint-config`. The readme has told you how to use this library
