### ISSUE TITLE
建议增加一个 ref定义的值 使用时未用.value 提示警告

### ISSUE THREAD

**Issue by weishaoy** [antfu/eslint-config#237]
### Clear and concise description of the problem

建议增加一个 ref定义的值 使用时未用.value 提示警告

### Suggested solution

建议增加一个 ref定义的值 使用时未用.value 提示警告

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Volar / TypeScript already covers it. It's not easy to do on eslint level, and I am not very interested in that. Thanks.
