### ISSUE TITLE
Add documentation for configuring https://typescript-eslint.io/linting/typed-linting/

### ISSUE THREAD

**Issue by laterdayi** [antfu/eslint-config#239]
### Clear and concise description of the problem

vue eslint does not work when typed-linting is configured

### Suggested solution

Add documentation for configuring https://typescript-eslint.io/linting/typed-linting/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
