### ISSUE TITLE
How do I configure eslint-plugin-n eslint-plugin-unicorn in antfu/eslint-config

### ISSUE THREAD

**Issue by laterdayi** [antfu/eslint-config#240]
### Clear and concise description of the problem

How do I configure eslint-plugin-n eslint-plugin-unicorn in antfu/eslint-config

I don't need to use these in my project

### Suggested solution

*

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
https://eslint.org/docs/latest/
