### ISSUE TITLE
Beta not working in CJS projects

### ISSUE THREAD

**Issue by codepunkt** [antfu/eslint-config#253]
### Describe the bug

Beta isn't working in CJS projects:

```terminal
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/christoph/projects/webpack-license-plugin/node_modules/@antfu/eslint-config/dist/index.js from /Users/christoph/projects/webpack-license-plugin/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported.
Instead change the require of index.js in /Users/christoph/projects/webpack-license-plugin/node_modules/@eslint/eslintrc/dist/eslintrc.cjs to a dynamic import() which is available in all CommonJS modules.
```

This is my eslint config, using eslint in version `8.49.0` and your config in any `1.0.0` beta version (works with `0.43.1`):

```js
module.exports = {
  extends: ['@antfu'],
}
```

### Reproduction

Run `npx eslint .` with the aforementioned eslint and config versions and the config shown above.

### System Info

```Shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 438.13 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.volta/tools/image/node/18.12.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/18.12.1/bin/npm
    pnpm: 8.6.10 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's now an ESM-only package and the Flat Config, and Flat Config isn't compatible with the legacy `extends`. https://eslint.org/docs/latest/use/configure/configuration-files-new

**Comment by codepunkt** [comment]
That's quite a change. There's gotta be ways of supporting the new configuration syntax for both CJS and ESM?

**Comment by antfu** [comment]
Shipped CJS build in 5cf471b078ba0e3505bbb5fd8a14615f95e5e5c3 to make it easier. But still, you will need to migrate to the FlatConfig. It's fundamentally better and much easier to maintain in the long term.

**Comment by codepunkt** [comment]
Awesome, gonna give it a shot later today!

**Comment by rubiin** [comment]
@antfu is there any example for using with commonjs

**Comment by rubiin** [comment]
this is the only solution i found so far:
`  "lint": "ESLINT_USE_FLAT_CONFIG=true eslint -c eslint.config.mjs '{src,test}/**/*.ts' --cache"` . Doent work with eslint extension though. Also you need to name the file .mjs

**Comment by antfu** [comment]
You should be able to use `eslint.config.js` with CJS: https://github.com/antfu/eslint-config#create-config-file

And you will need to add `"eslint.experimental.useFlatConfig": true,` in VS Code
