### ISSUE TITLE
Simplify/enable easy rules overrides

### ISSUE THREAD

**Issue by AlexandreBonaventure** [antfu/eslint-config#255]
### Clear and concise description of the problem

I recently wanted to migrate our eslint setup to use the new flat config (because it's the best :) ). Found your config in the perfect timing. We're building vite powered vue+ts app so most of your defaults suit us very well, but we have a couple opinionated rules that I'd like to modify. I was surprised that it was not as easy as I thought with the new flat config system for language scope rules.

Here's a minimal repro that is highlighting my problem: 
https://stackblitz.com/edit/stackblitz-starters-bcd913?file=eslint.config.js

Trying to override a TS rule to meet my requirements as such:
`'ts/consistent-type-definitions': ['error', 'type'],`
Running eslint throws this error:
<img width="943" alt="image" src="https://github.com/antfu/eslint-config/assets/4596409/ca43c4e4-2eeb-4600-8bbe-23559b99a601">

It seems like you can get around by making to specify the files pattern to ensure eslint is able to validate against a config that has the rule. see in the repro: 
<img width="802" alt="image" src="https://github.com/antfu/eslint-config/assets/4596409/5fc2992b-ba29-45bd-b26f-86100e0a753b">

This is not ideal and was hoping that I wouldn't have to do this. Here, I copy pasted the GLOB from your sources.

### Suggested solution

I believe we're all fairly new and not super familiar yet with flat config, so I am not 100% sure it is expected from eslint perspective (let me know if not). Assuming yes, I'm thinking this repo could provide api/recipe to ease the process of overriding specific rules.

Thinking about 2 possible solutions:
- allow to pass options in each tree-shaken config that will be merged
  eg: 
```js
  // eslint.config.js
  export default [
  ...typescript({
       rules: { 'ts/consistent-type-definitions': ['error', 'type'],  }
  }),
  ...vue(),
]
```

- export glob const so that we can at least reuse? (not a big fan of this one)

### Additional context

ps: Thanks for your work. I'm a big fan of unocss, just started sponsoring you :)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Made 6a72bf5c7cb9771086460406e731c3b5156855e6, 05073cde29e1ddca862662b3076ff8909ec72c6e and 3935399475575d7abdd3980e74b71598b5ea1e4d, it should make it easier.

**Comment by AlexandreBonaventure** [comment]
that was fast :D thanks!
