### ISSUE TITLE
beta version a published as latest version on NPM

### ISSUE THREAD

**Issue by Barbapapazes** [antfu/eslint-config#257]
### Describe the bug

Hello,

beta version a currently published as latest version on npm and it's annoying because when I install the config, a beta version is installed!

### Reproduction

https://www.npmjs.com/package/@antfu/eslint-config?activeTab=versions

### System Info

```Shell
/
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's intended. Semver and the version name should guard that already for existing projects.
