### ISSUE TITLE
webstorm 使用 @antfu/eslint-config 报错

### ISSUE THREAD

**Issue by liu-yuren** [antfu/eslint-config#268]
### Describe the bug

WebStorm 2023.2.1 

编辑器 error 信息

Error: ESLint configuration in .eslintrc » @antfu/eslint-config is invalid:
	- Unexpected top-level property "GLOB_ALL_SRC".

Referenced from: D:\vue3-template\vue3-elementPlus\.eslintrc

  "devDependencies": {
    "@antfu/eslint-config": "1.0.0-beta.18",
    "@tsconfig/node18": "^18.2.2",
    "@types/node": "^18.17.17",
    "@vitejs/plugin-vue": "^4.3.4",
    "@vue/tsconfig": "^0.4.0",
    "eslint": "^8.50.0",
    "npm-run-all2": "^6.0.6",
    "typescript": "~5.2.0",
    "vite": "^4.4.9",
    "vue-tsc": "^1.8.11"
  }

### Reproduction

WebStorm 2023.2.1   编辑器 error 信息  Error: ESLint configuration in .eslintrc » @antfu/eslint-config is invalid: 	- Unexpected top-level property "GLOB_ALL_SRC".  Referenced from: D:\vue3-template\vue3-elementPlus\.eslintrc    "devDependencies": {     "@antfu/eslint-config": "1.0.0-beta.18",     "@tsconfig/node18": "^18.2.2",     "@types/node": "^18.17.17",     "@vitejs/plugin-vue": "^4.3.4",     "@vue/tsconfig": "^0.4.0",     "eslint": "^8.50.0",     "npm-run-all2": "^6.0.6",     "typescript": "~5.2.0",     "vite": "^4.4.9",     "vue-tsc": "^1.8.11"   }

### System Info

```Shell
WebStorm 2023.2.1 

编辑器 error 信息

Error: ESLint configuration in .eslintrc » @antfu/eslint-config is invalid:
	- Unexpected top-level property "GLOB_ALL_SRC".

Referenced from: D:\vue3-template\vue3-elementPlus\.eslintrc

  "devDependencies": {
    "@antfu/eslint-config": "1.0.0-beta.18",
    "@tsconfig/node18": "^18.2.2",
    "@types/node": "^18.17.17",
    "@vitejs/plugin-vue": "^4.3.4",
    "@vue/tsconfig": "^0.4.0",
    "eslint": "^8.50.0",
    "npm-run-all2": "^6.0.6",
    "typescript": "~5.2.0",
    "vite": "^4.4.9",
    "vue-tsc": "^1.8.11"
  }
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by liu-yuren** [comment]
根目录 .eslintrc 文件

{
  "extends": "@antfu"
}

**Comment by liu-yuren** [comment]
按章文档 创建 eslint.config.js 文件

const antfu = require('@antfu/eslint-config').default

module.exports = antfu()

不报错啦 

但是

package.json 文件中 加上 "types": "module",

使用下面这种方式会报错

// eslint.config.js
import antfu from '@antfu/eslint-config'

export default antfu()

error 信息：SyntaxError: Cannot use import statement outside a module

**Comment by SHERlocked93** [comment]
俺也一样

**Comment by crayymumu** [comment]
Me too......

**Comment by banzhe** [comment]
SyntaxError: Cannot use import statement outside a module
是因为package.json里的type不是module
https://nodejs.org/api/packages.html#type

**Comment by zerotower69** [comment]
package.json type 设置为 “module”，就表示你要使用esm 的import，module.exports是commonjs，为此需要将文件名后缀从.js改为.cjs，表示你仍然使用commonjs，而不去检查esm是否合法。

**Comment by silenceSeal** [comment]
可以试试这个方法：
大概率是使用node18，20,22 的版本，在package.json,添加
overrides: {
       ...
	"eslint": "^9.6.0"
}
是eslint的版本兼容问题。
添加后不再报错。mac，windows 都试过，ok的。
