### ISSUE TITLE
Update to-be-deprecated values of `editor.codeActionsOnSave`

### ISSUE THREAD

**Issue by Dimava** [antfu/eslint-config#273]
### Clear and concise description of the problem

The descriptions of recommended `editor.codeActionsOnSave` settings shows

![image](https://github.com/antfu/eslint-config/assets/20068737/f0d2d481-74c9-4af3-a005-a713829e5774)

### Suggested solution

Replace `true` with `"explicit"` and `false` with `"never"` just as the texts suggests

### Alternative

Replace `"source.fixAll": true` with `"source.fixAll": "always"` to also format on autosave

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by promise96319** [comment]
Tip:

 You need update Visual Studio Code to version 1.83 or higher for this configuration to function correctly. 

Without the update, Visual Studio Code will be unable to recognize the configuration of "explicit" and "never", leading to a failure when running "pnpm run lint".

[Visual Studio Code updates](https://code.visualstudio.com/updates/v1_83)
