### ISSUE TITLE
CLI for quick scaffolding

### ISSUE THREAD

**Issue by antfu** [antfu/eslint-config#274]
```bash
npx @antfu/eslint-config init
```

That will install the deps, create `eslint.config.js`, and update the `.vscode/settings.json` automatically.

**Comment by Debbl** [comment]
Is it possible to have `eslint` folder like [shadcn/ui](https://ui.shadcn.com/), so that if I want to configure `tailwindcss` I can run like `npx eslint-config add tailwindcss` command and then create the configure in the `eslint` directory and install the appropriate dependencies.
