### ISSUE TITLE
max-len formating

### ISSUE THREAD

**Issue by GaborTorma** [antfu/eslint-config#275]
### Clear and concise description of the problem

Is it possible to use auto fix formater for max-len rules?

### Suggested solution

Like Prettier printWidth, but I don't want to use Prettier.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
You could manually enable it if you want https://eslint.org/docs/latest/rules/max-len

For me I prefer to handle line wraps manually (one of the reasons I don't use Prettier).

I think this is generally hard to get done right, ESLint's rule might not work perfectly (so as Prettier).

**Comment by GaborTorma** [comment]
Yes, I enable it with this config:

// eslint.config.js
import antfu from '@antfu/eslint-config'

```js
export default antfu({
  rules: {
    'max-len': ['error', { code: 100 }],
  },
})
```
Auto fix does not work, only show the error. I would like to enable auto fix and if it not correct I will set the eslint ignore.

**Comment by antfu** [comment]
Yeah, I hope someone would maintain a fixable version for that. But either way, it could be out-of-scope of this project. Thanks for bringing this up.
