### ISSUE TITLE
'unused-imports/no-unused-vars': 'off'  not work

### ISSUE THREAD

**Issue by Simon-He95** [antfu/eslint-config#276]
### Describe the bug

<img width="1626" alt="image" src="https://github.com/antfu/eslint-config/assets/57086651/9db86a94-4955-4cc8-ac19-7f63fd777a95">

In Unocss, I run `lint:fix`, will have many errors, but I find the rules are off.

### Reproduction

https://github.com/unocss/unocss

### System Info

```Shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 122.42 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/Library/Caches/fnm_multishells/67217_1696844413996/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/67217_1696844413996/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/67217_1696844413996/bin/npm
    pnpm: 8.7.6 - ~/simon/Github/unocss/node_modules/.bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
> I don't see the error on UnoCSS. Can you double check?

![屏幕录制2023-10-09 23 00 21](https://github.com/antfu/eslint-config/assets/57086651/dfb1d547-6de3-4405-950e-0a9d235c315a)

If I add examples to ignores, it will be fine

<img width="1127" alt="image" src="https://github.com/antfu/eslint-config/assets/57086651/3d686b8b-c18e-4228-a1f4-2b9c9f72bcb4">

**Comment by Simon-He95** [comment]
It shouldn't be a problem with eslint-config. It's because I packaged it locally and generated it `.next` was detected, but examples should be added to ignores in unocss.

**Comment by Simon-He95** [comment]
Maybe we should add .next directly to the global default ignores

**Comment by antfu** [comment]
Sure, pr welcome
