### ISSUE TITLE
[Flat config] `ignores` conflict with `rules`

### ISSUE THREAD

**Issue by ewilan-riviere** [antfu/eslint-config#280]
### Describe the bug

Hello!

I love your `eslint-config` and wanted to test the new flat config, even though it was still in beta. And I'm sorry if this issue is unwelcome, because yes, it's in beta and so I completely understand that it can be normal for now. But since I've really tried everything: searching the repository issues, different syntaxes for `ignores`, comparison with the eslint doc... It doesn't work.

I use `ignores` entry to ignore some files or directories and `rules` to set some custom rules. It seems that the `rules` conflict with the `ignores` entry.

This is an example for `eslint.config.js`

```js
// eslint.config.js
import antfu from '@antfu/eslint-config'

export default antfu({
  ignores: [
    'src/scripts/**/*',
  ],
  rules: {
    'node/prefer-global/process': 'off',
  },
})
```

If I comment `rules` entry, files into `src/scripts` will be ignored by eslint, but with `rules`, eslint try to scan these files.

### Reproduction

https://github.com/ewilan-riviere/eslint-config-minimal

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 281.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.9.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.96
    Safari: 17.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
> ### Describe the bug 描述错误
> Hello! 你好！
> 
> I love your `eslint-config` and wanted to test the new flat config, even though it was still in beta. And I'm sorry if this issue is unwelcome, because yes, it's in beta and so I completely understand that it can be normal for now. But since I've really tried everything: searching the repository issues, different syntaxes for `ignores`, comparison with the eslint doc... It doesn't work.我喜欢你的 `eslint-config` ，想测试新的平面配置，即使它仍处于测试阶段。如果这个问题不受欢迎，我很抱歉，因为是的，它处于测试阶段，所以我完全理解它现在可能是正常的。但是由于我真的尝试了一切：搜索存储库问题，不同的 `ignores` 语法，与eslint文档的比较......它不起作用。
> 
> I use `ignores` entry to ignore some files or directories and `rules` to set some custom rules. It seems that the `rules` conflict with the `ignores` entry.我使用条目来 `ignores` 忽略某些文件或目录并 `rules` 设置一些自定义规则。似乎与 `ignores` 条目 `rules` 冲突。
> 
> This is an example for `eslint.config.js`这是一个例子 `eslint.config.js`
> 
> ```js
> // eslint.config.js
> import antfu from '@antfu/eslint-config'
> 
> export default antfu({
>   ignores: [
>     'src/scripts/**/*',
>   ],
>   rules: {
>     'node/prefer-global/process': 'off',
>   },
> })
> ```
> 
> If I comment `rules` entry, files into `src/scripts` will be ignored by eslint, but with `rules`, eslint try to scan these files.如果我注释 `rules` 条目，eslint 将忽略 into `src/scripts` 中的文件，但使用 eslint 尝试 `rules` 扫描这些文件。
> 
> ### Reproduction 繁殖
> https://github.com/ewilan-riviere/eslint-config-minimal
> 
> ### System Info 系统信息
> ```shell
> System:
>     OS: macOS 14.0
>     CPU: (10) arm64 Apple M1 Pro
>     Memory: 281.83 MB / 16.00 GB
>     Shell: 5.9 - /bin/zsh
>   Binaries:
>     Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
>     npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
>     pnpm: 8.9.0 - ~/Library/pnpm/pnpm
>   Browsers:
>     Chrome: 116.0.5845.96
>     Safari: 17.0
> ```
> 
> ### Used Package Manager 使用的包管理器
> pnpm
> 
> ### Validations 验证
> * [x]  Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)遵守我们的行为准则
> * [x]  Read the [Contributing Guide](https://github.com/antfu/contribute).阅读贡献指南。
> * [x]  Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.检查是否还没有报告相同错误的问题，以避免创建重复项。
> * [x]  Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.检查这是否是一个具体的错误。对于问答，请改为打开 GitHub 讨论。
> * [x]  The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.提供的重现是错误的最小可重现性。

Hi, @ewilan-riviere , I think you should configure it like this and it will solve your problem

```
export default antfu({
  ignores: [
    'src/scripts',
  ],
}, {
  rules: {
    'node/prefer-global/process': 'off',
  },
})
```

**Comment by ewilan-riviere** [comment]
Thanks you, it works perfectly!
