### ISSUE TITLE
Add option for the "curly" rule

### ISSUE THREAD

**Issue by bux** [antfu/eslint-config#283]
### Clear and concise description of the problem

Since first using vitesse I really like working with this eslint config. But of course for some stylings I usually do some tweaks. Enforcing braces for if blocks is one of those.
Instead of having to maintain a forked or derived eslint config an option for the "curly" setting would be appreciated.

### Suggested solution

An implementation similar to
```js
 stylistic: {
    indent: 'xxx',
    quotes: 'xxx',
    curly: 'error'
  },
```
as done in [this commit](https://github.com/antfu/eslint-config/commit/bbac13209e21be4bf979427625ad559dbd4df8a1)

### Alternative

Adding a rule to the `eslint.config.js` could be an alternative, but it seems that a change for `curly` is not being picked up in the resulting config (e.g. when running `npx eslint --debug --print-config .\test.ts`)

```js
export default antfu(
  {
    rules: {
      "max-len": ["error", { code: 101 }], // this is being appended to the resulting config
      "curly": "error", // this is not
    },
  },
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by bux** [comment]
That is true.
Being able to e.g. set the `all` rule would be awesome:
https://eslint.org/docs/latest/rules/curly#all

**Comment by antfu** [comment]
For the specifically, I believe

```ts
export default antfu(
  {
    rules: {
      "curly": ["error", "all"],
    },
  },
)
```

Would be able to override it. Since this does not occur in multiple places nor have rules overrides, I don't think at this moment it needs to be an option. Thanks for bringing this up

**Comment by bux** [comment]
Thank you for taking the time to answer.
