### ISSUE TITLE
`vue/component-name-in-template-casing` for auto-imported components

### ISSUE THREAD

**Issue by vaibhav11s** [antfu/eslint-config#288]
### Clear and concise description of the problem

`vue/component-name-in-template-casing` doesn't work when the component is global or auto-imported (like in nuxt).

### Suggested solution

in `configs/vue.ts` we can provide the optional option to `registeredComponentsOnly` as `false`.
```json5
{
  "vue/component-options-name-casing": ["error", "PascalCase", {
    "registeredComponentsOnly": false,
  }]
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure, want to make a quick PR to update it directly? Thanks
