### ISSUE TITLE
espree template for vue parser

### ISSUE THREAD

**Issue by GaborTorma** [antfu/eslint-config#294]
### Clear and concise description of the problem

Performance drop when we use [Type Aware Rules](https://github.com/antfu/eslint-config#type-aware-rules).

### Suggested solution

10 times faster with espree template.

https://github.com/vuejs/vue-eslint-parser#parseroptionsparser

Add "espree" template for vue parser.

```js
      languageOptions: {
        parser: parserVue,
        parserOptions: {
          ecmaFeatures: {
            jsx: true,
          },
          extraFileExtensions: ['.vue'],
          parser: {
            '<template>': 'espree',
            'js': parserTs as any,
            'ts': options.typescript ? parserTs as any : null,
          },
          sourceType: 'module',
        },
      },
```

I tried to create a PR, but I got a ts error:
`src/configs/vue.ts(33,11): error TS2322: Type '{ '<template>': string; js: typeof parserTs; ts: any; }' is not assignable to type 'Parser | undefined'.`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure, PR welcome :)

**Comment by antfu** [comment]
https://github.com/antfu/eslint-config/pull/296#issuecomment-2312203148
