### ISSUE TITLE
`source.fixAll` may have dangerous behaviour

### ISSUE THREAD

**Issue by Dimava** [antfu/eslint-config#297]
### Describe the bug

Using `source.fixAll: true` may remove unreachable code ( https://github.com/microsoft/vscode/issues/159599 )
This issue is tagged "as-designed",  but may be very dangerous, as may randomly cut down a part of function of even a file

```ts
function foo(): never { throw 0 }

foo()
// happy debugging
foo() // disappears on save
```

### Suggested solution
Replace
```
"source.fixAll": "explicit",
```
with
```
"source.fixAll.eslint": "explicit",
```

### Reproduction

`alert("fine"); throw 0; alert("gets deleted") // save 5 times, 2nd alert gets deleted`

### System Info

```Shell
Every VSCode version since `1.70.2` (Aug 2022)
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
> "source.fixAll.eslint": "explicit",

Sure, PR welcome
