### ISSUE TITLE
feat: add eslint-plugin-no-await-in-promise

### ISSUE THREAD

**Issue by libondev** [antfu/eslint-config#311]
### Clear and concise description of the problem

https://x.com/alvarlagerlof/status/1720182566135779582?s=20

The reason is as above. I discovered this post while surfing the internet, and I believe it is a noteworthy issue, so I raised this issue

### Suggested solution

There are already ready-made implementations in the community, so I think we can extend the rules here.

https://github.com/hugo-vrijswijk/eslint-plugin-no-await-in-promise

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I might be biased, but I don't feel it's really helpful, as it's a bit niche and easy to spot isn't it? I don't feel it's worth it to introduce another dependency.

**Comment by libondev** [comment]
I think you're right👀
