### ISSUE TITLE
eslintrc.yml

### ISSUE THREAD

**Issue by steklopod** [antfu/eslint-config#312]
### Clear and concise description of the problem

After upgrade to version 1.0 I get an error:

> Error: ESLint configuration in .eslintrc.yml » @antfu/eslint-config is invalid:
        - Unexpected top-level property "GLOB_ALL_SRC".

I have `.eslintrc.yml` that works with prev. version. But there is no doc how to use `yml`. Could the instruction be added to readme?

### Suggested solution

Add instruction how to use  `.eslintrc.yml`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Dimava** [comment]
Readme
> [!IMPORTANT]
> Since v1.0.0, this config is rewritten to the new [ESLint Flat config](https://eslint.org/docs/latest/use/configure/configuration-files-new), check the [release note](https://github.com/antfu/eslint-config/releases/tag/v1.0.0) for more details.

**Comment by steklopod** [comment]
Thanks. So the issue can be closed
