### ISSUE TITLE
`extends` keyword in latest v. 1.0 (how to use plugins doc) 📃

### ISSUE THREAD

**Issue by steklopod** [antfu/eslint-config#313]
### Clear and concise description of the problem

After upgrade to **version 1.1.0** I can't find a documentation about how can I reuse `extends` section  from my previous config in my new `eslint.config.js`:

```yml
extends:
  - '@antfu'
  - plugin:nuxt/recommended  👈🏻👈🏻👈🏻
  - '@nuxtjs/eslint-config-typescript' 👈🏻👈🏻👈🏻
```

For these deps:
```js
    "@antfu/eslint-config": "1.1.0",
    "eslint": "8.53.0",
    "@nuxtjs/eslint-config-typescript": "12.1.0", 👈🏻👈🏻👈🏻
    "eslint-plugin-nuxt": "4.0.0",  👈🏻👈🏻👈🏻
```

___
Everything works except these plugins 🤷🏻

### Suggested solution

Add instruction how to use `extends` in version 1.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I believe that Flat Config does not support extends: https://eslint.org/docs/latest/use/configure/configuration-files-new

It would need the other configs to support flat config as well

**Comment by steklopod** [comment]
Thanks for the response 🙏🏻 So I just removed these deps & `extends` section
