### ISSUE TITLE
Type issue with `@typescript-eslint` `v6.11.0`

### ISSUE THREAD

**Issue by xsjcTony** [antfu/eslint-config#320]
### Describe the bug

Once you upgrade `@typescript-eslint` to `v6.11.0`, I believe you will receive the following error.
![image](https://github.com/antfu/eslint-config/assets/45784210/d0b02954-3721-4cfd-a1be-b603ce88b915)

This is due to they added their own type of `ParserOptions` interface: https://github.com/typescript-eslint/typescript-eslint/commit/66cd0c0535e5de1b46ba337919a9a92748d2b0a6#diff-0e798f552c8234481a38c25e7f1ab0656dc8704bee64c4750eeb895c36f8636a

And because we are importing from `@typescript-eslint/parser`, the types will be imported as well and resulting in conflicts when merging interfaces.

Any idea how we should work around it? manually import those exported JS members cannot avoid types to be imported.
Or should we make our `ParserOptions` interface name unique to avoid being merged?

### Reproduction

See above, just upgrade the `@typescript-eslint` version to the latest

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 11.34 GB / 31.69 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.58)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I suppose this no longer an issue? Feel free to bring it back if still
