### ISSUE TITLE
What is the best way to include @antfu/eslint-config into another shareable flat config?

### ISSUE THREAD

**Issue by stefanobartoletti** [antfu/eslint-config#329]
Hi, I'm trying to include your base config, together with some personal customizations, into another shareable config to use across my projects.

With `@antfu/eslint-config@` version `1.x` I was able to do so with something like this (it is a node module)

```js
//index,js

import antfu from '@antfu/eslint-config'

const myConfig = antfu({
  stylistic: true,
  vue: true,
  typescript: true,
},{
  // My custom rules
})

export default myConfig
```

Then in `eslint.config,js`:

```js
import myConfig from '@myConfig/eslint-config'

export default [
  ...myConfig,
]
```

This has a very clean synax in `eslint.config,js` that is very easily tweakable with custom rules on a per-project basis and it is very close to what eslint docs suggest for the configuration.

After your config migrated to an async function in `v.2`, this basic config is no longer working (both for eslint proper and for `eslint-flat-config-viewer`, ideally by keeping a minimal and clean syntax inside `eslint.config,js`

Are there some suggestions about how to properly do this? I guess that being your config very popular, this may be a topic worth dealing with an maybe documenting a bit. 

I am available to provide more information and testing if needed, and of course this is open to everyone may be in need of such thing, not just @antfu .

Thanks!

**Comment by antfu** [comment]
We provide a utility called combine to do so:

```ts
import { combine } from '@antfu/eslint-config'
import myConfig from '@myConfig/eslint-config'

export default combine(
  myConfig,
  {
    // other inline config
  }
)
```

Or you can also make a factory wrapper:

```ts
//index,js

import antfu from '@antfu/eslint-config'

const myConfig = (...args) => {
	return antfu({
	  stylistic: true,
	  vue: true,
	  typescript: true,
	},{
	  // My custom rules
	}, ...args)
}

export default myConfig
```

and

```ts
import myConfig from '@myConfig/eslint-config'

export default myConfig(
  // other inline configs
)
```

**Comment by stefanobartoletti** [comment]
Thanks for your help!

I have publicly released my own configuration, based on yours, with some optional rulesets for Nuxt and Tailwind.

If somebody else is interested, maybe only to have an example of how to create a shareable config based on yours, the repository is here:

https://github.com/stefanobartoletti/eslint-config
