### ISSUE TITLE
feat: merge eslintignore

### ISSUE THREAD

**Issue by Simon-He95** [antfu/eslint-config#332]
### Clear and concise description of the problem

For those who are accustomed to the use of the original eslintignore, they may need to configure ignores in the new function. They may not particularly want to use it. I hope it can be compatible with the use of eslintignore. Maybe it can support reading eslintignore to meger to ignores for compatibility. , this should make it easier to get started

### Suggested solution

For those who are accustomed to the use of the original eslintignore, they may need to configure ignores in the new function. They may not particularly want to use it. I hope it can be compatible with the use of eslintignore. Maybe it can support reading eslintignore to meger to ignores for compatibility. , this should make it easier to get started

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
You can add https://github.com/antfu/eslint-config-flat-gitignore yourself. I don't think it's a good practice to advocate something ESLint is dropping.
