### ISSUE TITLE
feat: add eslint-plugin-deprecation

### ISSUE THREAD

**Issue by rubiin** [antfu/eslint-config#334]
### Clear and concise description of the problem

Currently the only way to catch deprecated methods is by viewing the file . 

### Suggested solution

Usingf https://www.npmjs.com/package/eslint-plugin-deprecation helps  report usage of deprecated code.

### Additional context

I can create a PR real quick 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
This seems to require the start of a TypeScript server that might affect the performance, I am not so confident about having it as default. Feel free to install it locally on yourself. Maybe we could have a list of "Recommended Plugins" in the readme to help a bit of discovery?
