### ISSUE TITLE
 camelcase

### ISSUE THREAD

**Issue by yxl989458** [antfu/eslint-config#335]
### Clear and concise description of the problem

 camelcase close ?

### Suggested solution

 camelcase :'off'

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
?
