### ISSUE TITLE
编写 js 代码时，使用未定义变量没有报错

### ISSUE THREAD

**Issue by fkcaipiao** [antfu/eslint-config#350]
### Clear and concise description of the problem

编写 js 代码时，使用未定义变量没有报错。可参考下面的示例，c 是未声明的变量，并没有相关提示。

![image](https://github.com/antfu/eslint-config/assets/148044704/91c59293-1ba4-46d0-8310-54dd18fab387)

### Suggested solution

希望使用 js 时有更好的体验

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
You can enable it by yourself. I prefer to use TS for that.

**Comment by fkcaipiao** [comment]
> efer to use TS for that.

Some react native third-party libraries do not support TS well enough. I will enable it myself. Thanks for the reply.
