### ISSUE TITLE
Rule "indent" ArrayExpression not applied

### ISSUE THREAD

**Issue by Lozoute** [antfu/eslint-config#356]
### Describe the bug

With default configuration the rule "indent" does not apply on array expressions.
But the config viewer states that the rule is active, did I miss something?

We can this on the picture that the indent is not fixed on the fly:
![Capture d’écran 2023-12-09 à 20 22 07](https://github.com/antfu/eslint-config/assets/13406562/53eb2421-30d3-464a-9048-5b521e39b6d1)

But config viewer states that the rule is on:
![Capture d’écran 2023-12-09 à 20 20 28](https://github.com/antfu/eslint-config/assets/13406562/32e051e3-9c2f-4915-8e0c-6a989a1fa3f8)

But, if I setup the rule myself in the `eslint.config.js` file with:

> rules: {
>     indent: ["error", 2, { "ArrayExpression": 1 }]
>   }

It works

Did I miss something? Do I need to opt-in for stylistic rules somewhere?

### Reproduction

https://github.com/Lozoute/AntfuEslintReproduction

### System Info

```Shell
System:
    OS: macOS 13.5.2
    CPU: (12) arm64 Apple M2 Max
    Memory: 22.20 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.11.0 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.71
    Safari: 16.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It should be fixed I suppose
