### ISSUE TITLE
Consider adding some tool to sort CSS properties.

### ISSUE THREAD

**Issue by stefanobartoletti** [antfu/eslint-config#360]
### Clear and concise description of the problem

First of all thanks for integrating the ability to lint also CSS files in the latest versions.

I think it would be a nice thing to have some sort of preset for ordering CSS properties, in order to have a more logical disposition and also help with git merges.

In my current config based on stylelint I am using https://github.com/stormwarning/stylelint-config-recess-order
and it does the job very nicely.

### Suggested solution

Since at the moment you have included Prettier to lint CSS, you can consider this

https://github.com/Siilwyn/prettier-plugin-css-order 

which in turn seems to be based on the more generic PostCSS 

https://github.com/Siilwyn/css-declaration-sorter

If in the future you will consider dropping Prettier for good, another solution may need to be found, but at the moment this seems to be a nice solution

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by m-shum** [comment]
Stylelint integration would be greatly appreciated as currently it's unclear how to integrate stylelint with this module without enabling prettier (which causes formatting conflicts with this module).

**Comment by antfu** [comment]
Thanks for bringing this up - the context is that I don't write a lot of CSS, and I don't really have an incentive to support this. If it's not too complicated to introduce it and not very costly for performance, I am happy to accept a PR. Otherwise, I guess it's better to do it on user land.

**Comment by stefanobartoletti** [comment]
I must say that lately I don't write a lot of plain CSS myself, as I use mostly utilities-based frameworks.

So in the end this a "nice to have" rather than a needed feature, but it is helpful in the right context.

At the moment I don't think I have the capabilities to work on a PR myself, I never dug a lot into how Eslint work internally besides what is required user-wise. But maybe when I will be more free from regular work I can try to study it a little and see if it is doable, at least by me.

Thanks for your reply and for your availability, as always!

**Comment by antfu** [comment]
I am closing this for now as it's probably not in scope for us to keep tracking it - feel free to bring up again if there is a plugin for that later. Thanks
