### ISSUE TITLE
`stylistic/style` missing in `overrides`

### ISSUE THREAD

**Issue by mukundshah** [antfu/eslint-config#362]
### Describe the bug

This is the current state of `overrides`
```ts
 overrides?: {
     javascript?: FlatConfigItem['rules'];
     typescript?: FlatConfigItem['rules'];
     test?: FlatConfigItem['rules'];
     vue?: FlatConfigItem['rules'];
     jsonc?: FlatConfigItem['rules'];
     markdown?: FlatConfigItem['rules'];
     yaml?: FlatConfigItem['rules'];
     toml?: FlatConfigItem['rules'];
     react?: FlatConfigItem['rules'];
 }
 ```
 This is from version: `2.4.5`

### Reproduction

N/A

### System Info

```Shell
System:
    OS: macOS 13.6.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 39.86 MB / 20.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 21.4.0 - ~/.asdf/shims/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.4 - ~/.asdf/shims/npm
    pnpm: 8.12.0 - /usr/local/bin/pnpm
    bun: 1.0.15 - /usr/local/bin/bun
Browsers:
    Chrome: 119.0.6045.105
    Safari: 17.1.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Dimava** [comment]
Please implement this

People will keep reinventing this by the rule of the least astonishment 
You may limit it to `Pick<rules, `style/${string}`>` or in runtime to the ones making sense

workaround: #308

**Comment by antfu** [comment]
Added in a2d9b185b8205876e573edc374bc2cdfeb086511
