### ISSUE TITLE
If eslint script has `--cache` options, and the project has .md files, running it will report an error

### ISSUE THREAD

**Issue by hooray** [antfu/eslint-config#363]
### Describe the bug

package.json

```json
{
  "scripts": {
    "lint": "eslint . --cache --fix"
  }
}
```

eslint.config.js

```js
import antfu from '@antfu/eslint-config'

export default antfu()
```

and the project root directory has an empty .md file, such as `README.md`.

Run the script will report:

<img width="788" alt="image" src="https://github.com/antfu/eslint-config/assets/1574903/8849ad3b-0283-4a38-ac15-72d3484b459c">

---

This question started to appear in v2.4.0

### Reproduction

/

### System Info

```Shell
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 95.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/Library/Caches/fnm_multishells/75850_1702638116050/bin/node
    Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/75850_1702638116050/bin/yarn
    npm: 10.1.0 - ~/Library/Caches/fnm_multishells/75850_1702638116050/bin/npm
    pnpm: 8.12.1 - ~/Library/pnpm/pnpm
    bun: 1.0.1 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Fixed in 2.4.6
