### ISSUE TITLE
reportUnusedDisableDirectives - Invalid Options

### ISSUE THREAD

**Issue by rafalpiechowicz** [antfu/eslint-config#368]
### Describe the bug

After the upgrade a version to `2.4.6` of plugin eslint won't work and webstorm display a error:
`Error: Invalid Options: Unknown options: reportUnusedDisableDirectives`

There is my eslint config 
<img width="429" alt="image" src="https://github.com/antfu/eslint-config/assets/116646546/f059f95b-513c-4b97-b98c-d98042ae8c4b">

Anyone has a similar error? Or some suggestions what is wrong?

### Reproduction

"@antfu/eslint-config": "2.4.6"

### System Info

```Shell
System:
    OS: macOS 14.1.2
    CPU: (11) arm64 Apple M3 Pro
    Memory: 67.53 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.1.0 - /opt/homebrew/bin/node
    npm: 10.2.0 - /opt/homebrew/bin/npm
    pnpm: 8.10.5 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.1.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JobinJia** [comment]
I installed eslint version 8.55.0 to fixed . You can see [here](https://github.com/eslint/eslint/pull/17867#issuecomment-1863582496)

**Comment by rpiechowicz** [comment]
Yes, that works. Thanks a lot!
