### ISSUE TITLE
eslint Flat config移除了extends，那么在ESM的情况下，.eslintrc-auto-import.json怎么关联呢？

### ISSUE THREAD

**Issue by lubulikai** [antfu/eslint-config#370]
### Describe the bug

手动复制globals到 languageOptions内太麻烦了，目前是这么做的，有没有更好的办法？
![微信截图_20231222142137](https://github.com/antfu/eslint-config/assets/49059016/d7f00c0d-0504-466a-92f7-16743e2a0479)
![微信截图_20231222142257](https://github.com/antfu/eslint-config/assets/49059016/39d249cf-04bd-458e-bfbe-53fbe76a3886)
![微信截图_20231222142409](https://github.com/antfu/eslint-config/assets/49059016/932f9a41-a424-4568-b9bb-3aeee27c4919)

### Reproduction

"@antfu/eslint-config": "^2.4.6"

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 8.03 GB / 15.92 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE      
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.12.1 - C:\Program Files\nodejs\pnpm.CMD       
  Browsers:
    Edge: Chromium (120.0.2210.77)
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
You can use FlatCompat: https://github.com/antfu/eslint-config#create-config-file

**Comment by xiaofuyesnew** [comment]
@lubulikai 

If you can use node's import capability, you can also do this:

```javascript
import antfu from '@antfu/eslint-config'
import { globals } from './.eslintrc-auto-import.json' assert {type: 'json'}

export default antfu({
  ...,
  languageOptions:{
    globals
  }
})
```

**Comment by eachann1024** [comment]
> ### 描述错误
> 手动复制globals到 languageOptions内太麻烦了，目前是这么做的，有没有更好的办法？ ![微信截图_20231222142137](https://private-user-images.githubusercontent.com/49059016/292388962-d7f00c0d-0504-466a-92f7-16743e2a0479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjE5MjIsIm5iZiI6MTcxNTE2MTYyMiwicGF0aCI6Ii80OTA1OTAxNi8yOTIzODg5NjItZDdmMDBjMGQtMDUwNC00NjZhLTkyZjctMTY3NDNlMmEwNDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5NDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMDU4MTBkNjEyYTYwMmU3ZjY2ZmNlMDRkZTU4ZDlkM2M2YTJlMjY1MzRjZjEzYmQ2NjcwMDY1MWRlNTRmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EScND5TfUtq6LsNLh5xHA5W36rE6Do6gcFJps2byPLE) ![微信截图_20231222142257](https://private-user-images.githubusercontent.com/49059016/292389190-39d249cf-04bd-458e-bfbe-53fbe76a3886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjE5MjIsIm5iZiI6MTcxNTE2MTYyMiwicGF0aCI6Ii80OTA1OTAxNi8yOTIzODkxOTAtMzlkMjQ5Y2YtMDRiZC00NThlLWJmYmUtNTNmYmU3NmEzODg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5NDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNGYwYjg3ZmI3MmI3NzVjYzdhNDA4ZDQ0MTdjMWM4M2VhNTQ3YzVmMDcyNTkzZDI2YmVkNTM4YjFlZDZmMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nd9YiLDiAPk9-yshJayJplS0V8J-epyISCyFv-taNZU) ![微信截图_20231222142409](https://private-user-images.githubusercontent.com/49059016/292389422-932f9a41-a424-4568-b9bb-3aeee27c4919.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjE5MjIsIm5iZiI6MTcxNTE2MTYyMiwicGF0aCI6Ii80OTA1OTAxNi8yOTIzODk0MjItOTMyZjlhNDEtYTQyNC00NTY4LWI5YmItM2FlZWUyN2M0OTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5NDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZWE3YmMzZWJjOGI3NmQzYjZmOThmOGQ4NGU5ODk3ZDQwNWE5Y2Q2OTc3ZjU3MjkxNjRlMzExOWIxZTFjYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5GcNYeOY4te7tZG8xju8HEbRx8TBtNSs9Xb3rnt_Pz8)
> 
> ### 繁殖
> “@antfu/eslint-config”： “^2.4.6”
> 
> ### 系统信息
> ```shell
> System:
>     OS: Windows 10 10.0.19045
>     CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
>     Memory: 8.03 GB / 15.92 GB
>   Binaries:
>     Node: 20.10.0 - C:\Program Files\nodejs\node.EXE      
>     npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
>     pnpm: 8.12.1 - C:\Program Files\nodejs\pnpm.CMD       
>   Browsers:
>     Edge: Chromium (120.0.2210.77)
>     Internet Explorer: 11.0.19041.3636
> ```
> 
> ### 使用的包管理器
> PNPM的
> 
> ### 验证
> * [x] 遵守我们[的行为准则](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
> * [x] 阅读[贡献指南](https://github.com/antfu/contribute)。
> * [x] 检查是否尚不存在报告相同 bug 的问题，以避免创建重复项。
> * [x] 检查这是否是一个具体的错误。如需问答，请改为打开 GitHub 讨论。
> * [x] 提供的复制品是 bug 的[最小可重现](https://stackoverflow.com/help/minimal-reproducible-example)性。

请问最终是怎么解决的? 看文档没get到

**Comment by CoderWeiJ** [comment]
```typescript

// eslint.config.mjs
import antfu from '@antfu/eslint-config'
import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat()

export default antfu(
  {
    ignores: [],
  },

  // Legacy config
  ...compat.config({
    extends: [
      'eslint:recommended',
      // Other extends...
    ],
  })

  // Other flat configs...
)
```

**Comment by xiaofuyesnew** [comment]
实际上可以这样配置 `unplugin-auto-import` ：
```js
AutoImport({
  //...
  eslintrc: {
    enabled: true,
    filepath: './.eslintrc-auto-import.js',
  }
})
```
