### ISSUE TITLE
Should Ignore js files for type awared rules

### ISSUE THREAD

**Issue by mutoe** [antfu/eslint-config#375]
### Describe the bug

When I assign a tsconfig path to `typescript` option. It told me I should include the js file to tsconfig.json
<img width="968" alt="image" src="https://github.com/antfu/eslint-config/assets/9391981/3a150c21-ce0a-4055-8980-5fdc6663bfb0">

However, after I include the js files in tsconfig. It told me there has some types is unsafe, like this
<img width="953" alt="image" src="https://github.com/antfu/eslint-config/assets/9391981/78ef270b-ef6f-403c-96cc-7cb4ab810654">

Actually I don't really want to check the js files' type. I'm not sure if this is expected behavior or a bug.

Happy to contribute if it is a bug :)

### Reproduction

https://github.com/mutoe-archive/antfu-eslint-config-type-aware-in-js-issue

### System Info

```Shell
N/A
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Dimava** [comment]
I guess it's mostly trying to say you are missing `@types/node` devDependency

I do agree config should not chech ts rules on js files by default unless you have allowJs on, so you don't have to make `eslint.tsconfig.json` just to make it not crash on `eslint.config.js`

**Comment by mutoe** [comment]
> I guess it's mostly trying to say you are missing `@types/node` devDependency

I don't think this is `@types/node` issue. Still having this error after I installed it.
 
> so you don't have to make `eslint.tsconfig.json` just to make it not crash on `eslint.config.js`

What's you mean? Whether I include that js file or not, it gives an error, like I said in the post.

**Comment by Dimava** [comment]
The problem is there is no easy way to not typecheck JS files

@mutoe 
```ts
import antfu from '@antfu/eslint-config'

export default antfu({
  typescript: {
    tsconfigPath: './tsconfig.json',
  },
  // overrides: {
  //   javascript: {
  //     'ts/no-unsafe-argument': 'off', // won't work
  //   },
  // },
}, {
  files: ['**/*.js'],
  rules: {
    'ts/no-unsafe-argument': 'off',
    'ts/no-unsafe-assignment': 'off',
    'ts/no-unsafe-call': 'off',
    'ts/no-unsafe-member-access': 'off',
    'ts/no-unsafe-return': 'off',
  },
})
```
will work

@antfu please add some easy way to exclude 
```diff
 export async function typescript(
   options: OptionsFiles & OptionsComponentExts & OptionsOverrides & OptionsTypeScriptWithTypes & OptionsTypeScriptParserOptions = {},
 ): Promise<FlatConfigItem[]> {
   const {
     componentExts = [],
     overrides = {},
     parserOptions = {},
+    excludes = [], // e.g. `['**/*.js']` or `['./*.js']` to exclude files that are not in tsconfig
   } = options
 
   const files = options.files ?? [
-    GLOB_SRC,
+    options.typecheckJs ? GLOB_SRC : GLOB_TS, // some way to disable type-aware-rules for JS as they are often configs/scrips outside of the project. Currently you *have* to add eslint.config.js into tsconfig or it gonna bark
     ...componentExts.map(ext => `**/*.${ext}`),
   ]
```
