### ISSUE TITLE
Nuxt 3 TS error/conflict with eslint.config.js

### ISSUE THREAD

**Issue by juretopolak** [antfu/eslint-config#376]
Hi! 👋

I'm using antfu/eslint-config in a Nuxt 3 project. It seems there is some kind of conflict with `eslint.config.js`:

![Screenshot 2023-12-27 at 11 12 18](https://github.com/antfu/eslint-config/assets/46278375/a7a9ac5e-20bf-46e0-b32e-46c18c68f216)

I've followed the steps in the documentation to configure it... but as a "newcomer", I may have misconfigured something.

The TS error appears in the file `server/tsconfig.json`:
> Cannot write file '/Users/jure/Code3/nuxt-antfu-eslint/eslint.config.js' because it would overwrite input file.ts

It's strange that the error only appears when any .ts file in the ./server/ folder is opened with VSCode.

I'm wondering if anyone else has the same problem or is this the issue with my VSCode...

This is a minimal demo project to quickly reproduce the error (containing only Nuxt 3 and @antfu/eslint-config):

https://github.com/juretopolak/nuxt-antfu-eslint

**Comment by so1ve** [comment]
Add `"noEmit": true` to your `tsconfig.json`:

```json
{
  "compilerOptions": {
    "noEmit": true
  }
}
```

**Comment by Dimava** [comment]
For me thil looks like #380 / #384

**Comment by juretopolak** [comment]
@so1ve thank you, this works and I can finally get rid of the annoying ESLint error. 🙂
