### ISSUE TITLE
Top-level `ignores`

### ISSUE THREAD

**Issue by Dimava** [antfu/eslint-config#381]
### Clear and concise description of the problem

Currently globally excluding files requires knowing the "hack" to write them into their own ignores item

### Suggested solution

Add `ignores` property to the first `antfu()` arg that adds additional `..., { ignores: ... }, ...` (or as `ignores()` arg )

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Dimava** [comment]
This is `ignores` (was a typo), but the issue is correct

**Comment by antfu** [comment]
What do you mean?

**Comment by Dimava** [comment]
🤔
Nevermind, I forgot that first item is used as an regular items 
so you can simply use ignores as long as you don't add rules there
Was a bit sleepy when opened the issue
