### ISSUE TITLE
How do I keep only the indent rules of prettier or set them to the same effect of prettier using style/indent

### ISSUE THREAD

**Issue by laterdayi** [antfu/eslint-config#387]
### Clear and concise description of the problem

How do I keep only the indent rules of prettier or set them to the same effect of prettier using style/indent

### Suggested solution

How do I keep only the indent rules of prettier or set them to the same effect of prettier using style/indent

### Alternative

How do I keep only the indent rules of prettier or set them to the same effect of prettier using style/indent

### Additional context

How do I keep only the indent rules of prettier or set them to the same effect of prettier using style/indent

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by laterdayi** [comment]
```
    onUpdateValue: (value: (string | number | null)[]) => {
        if (formData.value) formData.value.eqpIds = [];
        value?.length
          ? executeGetEquipmentNumberChildList(__, {
              params: { LayoutId: value, check: '1' }
            })
          : handleQueryEquipmentNumberList();
      }
```


```
    onUpdateValue: (value: (string | number | null)[]) => {
        if (formData.value) formData.value.eqpIds = [];
        value?.length
          ? executeGetEquipmentNumberChildList(__, {
            params: { LayoutId: value, check: '1' }
          })
          : handleQueryEquipmentNumberList();
      }
```

I wanted to keep the top style, but now it's the bottom style

**Comment by thenbe** [comment]
For best results, you should use _either_ prettier _or_ eslint stylistic rules (`style/*`), not both.

For even better results, don't use prettier at all and configure your indent rules like [this](https://github.com/antfu/eslint-config/blob/cb651f434e389c80e063edc1c17b84d268ebb5fa/README.md?plain=1#L180-L183).

**Comment by thenbe** [comment]
> this whole linting and styling business with all it's plethora of config/plugin packages, is at times more complicated than programming itself.

This is exactly why I'm using this project (antfu/eslint-config) :)

---

All those things you mentioned, you can just get rid of them:

```sh
npm rm eslint-config-prettier eslint-plugin-prettier prettier
rm -f .prettierrc .prettierignore
```

For vscode, just turn off anything prettier and only leave eslint. I don't use vscode so I'm not sure how exactly, but you can take probably inspiration from [here](https://github.com/antfu/vscode-settings/blob/main/.vscode/settings.json) (search for `prettier`, `eslint` in that file for the relevant settings).

**Comment by laterdayi** [comment]
@thenbe  But using style/* does not indent the first effect
![image](https://github.com/antfu/eslint-config/assets/20943608/99a424ac-5c82-4993-ab48-751da6892cdf)

**Comment by Dimava** [comment]
@laterdayi try https://eslint.style/rules/js/indent#flatternaryexpressions

**Comment by laterdayi** [comment]
@Dimava  Still can't achieve this effect, can you help me

**Comment by laterdayi** [comment]
```
value?.length
          ? executeGetEquipmentNumberChildList(__, {
            params: { LayoutId: value, check: '1' }
          })
          : handleQueryEquipmentNumberList();
```

`  'style/indent': ['error', 2, { 'flatTernaryExpressions': false, offsetTernaryExpressions: true }],`

**Comment by laterdayi** [comment]
```
        value?.length
          ? executeGetEquipmentNumberChildList(__, {
              params: { LayoutId: value, check: '1' }
            })
          : **handleQueryEquipmentNumberList();
```

![image](https://github.com/antfu/eslint-config/assets/122137647/869f2474-95c8-412c-9581-86b2ac15368f)
I expected that, but it prompted an error

**Comment by Dimava** [comment]
@laterdayi it should autofix the error on save
Is there a rule conflict? I.e. does it reformat back to the code you don't want? Check what rule is that, you may need to disable it, or you may be using the wrong indent rule (you may need style/ts/indent or whatever)

**Comment by laterdayi** [comment]
It fixes itself, but it fixes the wrong thing
It can't be fixed like this

```
value?.length
          ? executeGetEquipmentNumberChildList(__, {
              params: { LayoutId: value, check: '1' }
            })
          : **handleQueryEquipmentNumberList();
```

**Comment by antfu** [comment]
Thanks for bringing this up. However, this is a bit too niche as a style preference, and this repo might not be the best place to discuss it. If there is nonexisting config that can make it work, you won't need to write your custom plugins. Either way, I consider this out-of-scope.
