### ISSUE TITLE
[Feature Request] disable use globals var `__dirname` `__filename` in nodejs esm mode

### ISSUE THREAD

**Issue by BobDu** [antfu/eslint-config#390]
### Clear and concise description of the problem

disable use globals var `__dirname` `__filename` in nodejs esm mode

These CommonJS variables are not available in ES modules.
https://nodejs.org/api/esm.html#no-__filename-or-__dirname

Suggest use `import.meta.filename` `import.meta.dirname` instead

Link: eslint-community/eslint-plugin-n#164

### Suggested solution

N/A

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by BobDu** [comment]
@antfu 
I'm very sorry to disturb you. I hope this doesn't cause any inconvenience for you. 
I would like to know if this feature request is easy to implement. Is it possible that it will be supported?

**Comment by antfu** [comment]
I'd be happy to disallow __dirname et al., but I am not sure if we should recommend `import.meta.filename` as it would be still runtime-specific. I usually use `new URL('../', import.meta.url)` to make it work cross platform.

**Comment by BobDu** [comment]
Sorry, I am not an experienced front-end developer. I trust that the usage you recommended is surely better. 

The idea behind this feature request originated from a bug I encountered during a migration from CommonJS to ESM.

Ref:
https://github.com/Kerwin1202/chatgpt-web/issues/405

**Comment by antfu** [comment]
I think currently I don't want to have a strict rule for that - feel free to disable it on userland.
