### ISSUE TITLE
Ignores not work as expected

### ISSUE THREAD

**Issue by brokuka** [antfu/eslint-config#394]
### Describe the bug

Prop `ignores` not working as expected and i'm getting `eslint` comment errors when not need

### Reproduction
https://github.com/brokuka/antfu-ignores-issue

Check  `~/generated/api/client.ts` to see if there is an error. Generated by `pnpm run generate:api`.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 165.75 MB / 15.92 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by brokuka** [comment]
Problem with relative paths. @antfu fix please in the docs, thank you.

**Comment by phk422** [comment]
I had the same problem

**Comment by yandixuan** [comment]
@brokuka try `'**/generated/**/*.ts'`

**Comment by 1nusah** [comment]
hello guys, facing this same issue. This is my eslint config

`import antfu from '@antfu/eslint-config'

export default antfu({
  ignores: [
    './api-reference/*.ts',
    './components/modules/teller/**',
    './pages/teller/**',
    './pages/utilities/**',
    './pages/customer-service/cheque-management/**',
    './pages/retail-banking/cheque-management/**',
    '/components/modals/billing/**',
    './components/ui/form/**',
  ],
  rules: {
    'vue/custom-event-name-casing': 'off',
    'no-console': ['error', { allow: ['warn', 'info'] }],
    'eslint-comments/no-unlimited-disable': 'off',
    'vue/no-export-in-script-setup': 'warn',
    'symbol-description': 'warn',
  },
})
`

**Comment by codeflorist** [comment]
@antfu 
i want to ignore the public folder.

i'm trying this in my config:
```js
export default antfu({
	ignores: [
		'**/public/**',
		'**/public/**/*',
		'public/**',
		'public/**/*',
	],
        ...
```
nothing seems to be working.
