### ISSUE TITLE
Svelte conflicting indentation rule (`svelte/indent` & `style/indent`)

### ISSUE THREAD

**Issue by Gerbuuun** [antfu/eslint-config#399]
### Describe the bug

I've encountered conflicting rules when using svelte.
I had a nested ternary in a svelte file (since removed because it is unreadable).
The indentation rules of `svelte/indent` and ` style/indent` are conflicting

```ts
const someVal: boolean | SomeObj = false;
const test
    = someVal === true
      ? 'some different value'
      : someVal === false
      ? undefined
      : someVal;
```

`style/indent` requires the nesting to be indented further while `svelte/indent` requires flat indentation.

### Reproduction

See description

### System Info

```Shell
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 82.67 MB / 16.00 GB
    Shell: 3.7.0 - /opt/homebrew/bin/fish
Binaries:
    Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
    Yarn: 3.2.3 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v21.2.0/bin/npm
    pnpm: 8.14.3 - ~/Library/pnpm/pnpm
    bun: 0.2.2 - ~/.bun/bin/bun
Browsers:
    Brave Browser: 120.1.61.109
    Safari: 17.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by thenbe** [comment]
I can repro as well. `style/indent` [should](https://sveltejs.github.io/eslint-plugin-svelte/rules/indent/) be turned off in favor of `svelte/indent` in svelte files.
