### ISSUE TITLE
VSCODE_PID is not present in SSH

### ISSUE THREAD

**Issue by kehwar** [antfu/eslint-config#401]
https://github.com/antfu/eslint-config/blob/ab920d96451e58648ecc5281c19344919c477111/src/factory.ts#L60

`VSCODE_PID` is not present in SSH, so editor autodetect doesn't work

Using `!!process.env.VSCODE_CWD` works for me, but I'm not sure is the correct fix for this

**Comment by antfu** [comment]
Ok, PR welcome :)
