### ISSUE TITLE
Using ignores in conjunction with rules leads to both not working

### ISSUE THREAD

**Issue by codeflorist** [antfu/eslint-config#403]
### Describe the bug

i'm getting very weird behavour, when using `ignores` in conjunction with `rules`.

this works to ignore all files:
```js
export default antfu({
	ignores: [
		'**/*',
	],
})
```

this rule is working:
```js 
export default antfu({
	rules: {
		'antfu/top-level-function': 'off',
	},
})
```

but when both are stated, both are ignored:

```js
export default antfu({
	ignores: [
		'**/*',
	],
	rules: {
		'antfu/top-level-function': 'off',
	},
})
```

this works however:
```js
export default antfu({
	ignores: [
		'**/*',
	],
}, {
	rules: {
		'antfu/top-level-function': 'off',
	}
})
```

but it is not really intuitive, and it's misleading, that interface `FlatESLintConfigItem` has both a `ignores` and a `rules` property.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-xlesw6?file=eslint.config.js

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by markthree** [comment]
The same problem occurs with [tov-ui](https://github.com/dishait/tov-ui)，When I get through this busy time, I will try to mention pr to fix the problem!

**Comment by antfu** [comment]
This is how flat config works: https://eslint.org/docs/latest/use/configure/configuration-files-new#configuration-objects

When `ignores` is the only property of that item, it applies to all files. When rules exists, it apply only to that rule.

**Comment by codeflorist** [comment]
Ah, ok. Thanks for the explanation, and sorry for the unnecessary issue!

**Comment by JiuRanYa** [comment]
If i need to not lint /public with this eslint-config top level, what should i do

**Comment by codeflorist** [comment]
> If i need to not lint /public with this eslint-config top level, what should i do

@JiuRanYa this should work:

```js
export default antfu(
  {
    ignores: [
      'public',
    ],
    // put your normal config here
  },
  {
    rules: {
      //put your rule configs here
    }
  }
)
```

**Comment by xiangshu233** [comment]
@codeflorist  I still don't quite understand, " If ignores is used without files and there are other keys (such as rules), then the configuration object applies to all linted files except the ones excluded by ignores, for example:"
```js 
export default [
    {
        ignores: ["**/*.config.js"],
        rules: {
            semi: "error"
        }
    }
];
What this means is that if you use ignores in your ESLint configuration to exclude certain files, and also specify other keys (such as rules), then that configuration object will apply to all linted files except those excluded by ignores.

This configuration means that the rule applies to all files, but excludes files ending with .config.js

This is the intuitive configuration，But this does not work

Must have
```js
export default antfu(
  {
    ignores: [
      'public',
    ],
    // put your normal config here
  },
  {
    rules: {
      //put your rule configs here
    }
  }
)
```
Why is this? Thanks for your advice.

**Comment by xiangshu233** [comment]
@codeflorist I still don't quite understand, " If ignores is used without files and there are other keys (such as rules), then the configuration object applies to all linted files except the ones excluded by ignores, for example:"
```js
export default [
    {
        ignores: ["**/*.config.js"],
        rules: {
            semi: "error"
        }
    }
];
```
What this means is that if you use ignores in your ESLint configuration to exclude certain files, and also specify other keys (such as rules), then that configuration object will apply to all linted files except those excluded by ignores.

This configuration means that the rule applies to all files, but excludes files ending with .config.js

This is the intuitive configuration，But this does not work

Must have
```js
export default antfu(
  {
    ignores: [
      'public',
    ],
    // put your normal config here
  },
  {
    rules: {
      //put your rule configs here
    }
  }
)
```
Why is this? Thanks for your advice.
