### ISSUE TITLE
Parsing error with nuxt-module

### ISSUE THREAD

**Issue by GaborTorma** [antfu/eslint-config#415]
### Describe the bug

Hi, thanx for your awesome repo.

I found a parsing error when I use your eslint-config with nuxt-module. I generated it by the .
You can check it with my minimal repo. It generated a new nuxt module based on [Module Author Guide](https://nuxt.com/docs/guide/going-further/modules), I installed the eslint-config, add the type aware rules and create a .d.ts definition file for the nuxt plugin.
You need to start only,  startCommand is set in StackBlitz, you will see the error message in the terminal.

Thanx!
Gábor

### Reproduction

https://stackblitz.com/~/github.com/GaborTorma/eslint-config-nuxt-module-error

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (32) x64 Intel(R) Core(TM) i9-14900K
    Memory: 22.24 GB / 31.22 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.11.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.5.0 - /usr/bin/npm
    pnpm: 8.15.4 - /usr/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.94
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It should be fixed in the latest versions.
