### ISSUE TITLE
Make configurable behaviour to show errors in editor or not

### ISSUE THREAD

**Issue by AlexMarlow25** [antfu/eslint-config#422]
### Clear and concise description of the problem

In our project we encountered non-obvious behavior of eslint work across developers. Because we use both editors in our work, WebStorm and VSCode, we get different ESLint behaviours. I described this more detailed in the [microsoft/vscode-eslint](https://github.com/microsoft/vscode-eslint/issues/1767) issue. In short - we get some errors in the WebStorm, but don't in the VSCode. And my first thought was - it is a problem on VSCode's side. But I was a little upset, when I saw [`isInEditor`](https://github.com/antfu/eslint-config/blob/0cecf1a5a2a1e6e002be71c9e2b6520fcbfa565a/src/factory.ts#L62) logic. Do we really need this inside this library if we can turn off these errors in the editor by ourselves, for example?
Anyway, if it works as intended and we don't want to change anything in the config logic, I think there is a bug with defining the `JETBRAINS_IDE` variable. But we need to test it to be sure.

### Suggested solution

Make it configurable by some property in the config options.

### Alternative

Remove this behavior and leave it to the user's choice.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
The condition is provided as the default value, which means you can disable it by providing `isInEditor: false` in the factory

**Comment by yunsii** [comment]
Why would you want the editor and the command line to behave differently? And I think almost nobody known the side effects controled by `isInEditor` 😂

**Comment by thenbe** [comment]
> Why would you want the editor and the command line to behave differently by default?

It won't make sense until you use a pre-commit hook, as described [here](https://github.com/antfu/eslint-config/blob/0cecf1a5a2a1e6e002be71c9e2b6520fcbfa565a/README.md?plain=1#L509-L531). Then it makes a lot of sense.

Some rules you want to enforce in a codebase, but do not want to run on-save. A prime example is `no-unused-imports`. You don't want it running on-save because that can get noisy/tiresome when your imports keep getting removed while you're actively writing code. Instead, you disable it in your editor and let your pre-commit hook handle it automatically.

**Comment by yunsii** [comment]
I see, it seems that `isInEditor: true` must work with pre-commit hook `eslint --fix`. But I am still use `eslint` only in pre-commit hook.

**Comment by antfu** [comment]
Because in editor you don't always want unused variables/imports to be removed as you are probably on the process of refactoring that you are going to use it soon. It's my workflow and I found it better that way - and you can disable that anyway.

**Comment by yunsii** [comment]
> Because in editor you don't always want unused variables/imports to be removed

I've got used to it 😂

After understand the purpose, I think this feature is pretty useful, and I have fixed the git `pre-commit` usage for my latest project, *use `eslint --fix` to replace just run `eslint` directly*. Maybe such details should be indicated in the documentation?

**Comment by antfu** [comment]
> Maybe such details should be indicated in the documentation?

You mean the editor's conditional behavior? Yeah totally, and PR welcome :)

**Comment by yunsii** [comment]
Furthermore, `isInEditor` should alse support WebStorm. But I didn't use it 😂
