### ISSUE TITLE
Use this with unplugin-auto-import/vite, not found onUpdated.

### ISSUE THREAD

**Issue by my-name-is-alan** [antfu/eslint-config#426]
### Describe the bug

when i use onUpdated lifecycle, eslint notice this:

<img width="776" alt="image" src="https://github.com/antfu/eslint-config/assets/152274630/57f4e00e-e37e-48bf-a905-9234f1312500">

i checked .eslintrc.auto-import.json. like this:
<img width="431" alt="image" src="https://github.com/antfu/eslint-config/assets/152274630/1dd90d8a-acd6-423c-9548-4ab324da25e0">
and eslint.config.js
<img width="866" alt="image" src="https://github.com/antfu/eslint-config/assets/152274630/1f5c9c40-76a1-45e5-a2e2-847a01ddf19b">

what can i do？pls。

### Reproduction

sry. this project is privite,i can`t  provide this.

### System Info

```Shell
System:
    OS: macOS 14.2.1
    CPU: (10) x64 Apple M2 Pro
    Memory: 71.00 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.volta/tools/image/node/14.21.3/bin/node
    npm: 6.14.18 - ~/.volta/tools/image/node/14.21.3/bin/npm
    pnpm: 8.6.12 - ~/.volta/bin/pnpm
    bun: 1.0.4 - ~/.bun/bin/bun
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.2.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
You better use TypeScript. I have no interest in solving "no-undef" issues
