### ISSUE TITLE
 style/max-statements-per-line errors not autofixed in unnamed components

### ISSUE THREAD

**Issue by m-shum** [antfu/eslint-config#427]
### Describe the bug

The following was noted in unnamed components such as `.js `files in the `/utils` or `/plugins` directories.

### Expected behavior:
Functions with miltiple statements are autofixed. For example:
```
function foo() {return 'bar'}
```
Should be autofixed to 
```
function foo() {
   return 'bar'
}
```

### Actual behavior:
Single-line functions are not autofixed. Linter throws the following error when running lint command: 
```
error  This line has 2 statements. Maximum allowed is 1  style/max-statements-per-line
```

### Reproduction

https://stackblitz.com/edit/nuxt-ui-1rqvm8?file=package.json,eslint.config.js,utils%2Fbem.js

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by thenbe** [comment]
The `max-statements-per-line` rule is not "auto-fixable", according to the table found on this [page](https://eslint.style/packages/default).

Perhaps you can open a feature request in that [repo](https://github.com/eslint-stylistic/eslint-stylistic) instead?

**Comment by m-shum** [comment]
> The `max-statements-per-line` rule is not "auto-fixable", according to the table found on this [page](https://eslint.style/packages/default).
> 
> Perhaps you can open a feature request in that [repo](https://github.com/eslint-stylistic/eslint-stylistic) instead?

Interestingly this rule rule is enforced & autofixed by stackblitz – perhaps something similar could be achieved here? If not, then documentation needs to be updated regarding this rule because the [rule declaration as described by Stylistic](https://eslint.style/rules/default/max-statements-per-line#max) does not work with this config since [Stylistic gets namespaced to 'style' here](https://github.com/antfu/eslint-config/blob/main/eslint.config.ts) [line 28].

**Comment by thenbe** [comment]
Is stackblitz using a different source for this rule (different plugin)?

As for configuration, does something like this not work for you? https://github.com/edwinhuish/better-comments-next/blob/600d37a94dfe7ed101d8af1f23d21d8451c5d093/eslint.config.js#L14

**Comment by antfu** [comment]
In a way, `function foo() {` is not a "statement" - which I think the current behavior actually makes sense to the rule's descriptions. You might want to write your own rule to do this, I don't have incentive to work on that. Thanks.
