### ISSUE TITLE
unused-imports/no-unused-imports not working

### ISSUE THREAD

**Issue by edwinhuish** [antfu/eslint-config#428]
### Describe the bug

eslint doesn't remove the unused import after formated.

### Reproduction

https://github.com/edwinhuish/antfu-eslint-test

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 3.39 GB / 23.96 GB
  Binaries:
    Node: 19.8.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.1.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by thenbe** [comment]
This rules is de-activated while inside your editor (to reduce [noise](https://github.com/antfu/eslint-config/issues/422#issuecomment-1998895883)). When you run eslint on the command line (whether manually or through a pre-commit hook) this rule is active:

```sh
pnpm eslint .

# or to remove the unused import automatically
pnpm eslint --fix .
```

Also see:
- https://github.com/antfu/eslint-config/pull/424/files
