### ISSUE TITLE
Tailwindcss Automatic Class Sorting with Prettier

### ISSUE THREAD

**Issue by TiroZit** [antfu/eslint-config#431]
### Clear and concise description of the problem

Hi.
It would be cool to add auto sorting of tailwind classes

### Suggested solution

https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sorry, I am not interested in including tailwind support built-in. @DavidDeSloovere already gave a decent example of how you can do it on user land.
