### ISSUE TITLE
eslint后续版本将会删除格式化规则

### ISSUE THREAD

**Issue by xiaoguaishou404** [antfu/eslint-config#435]
AnthonyFu你好，
eslint后面的新版本，将删除一些格式化的规则，那@antfu/eslint-config这个项目是不是就不能兼容用于最新版本的eslint了呢？

https://eslint.org/blog/2023/10/deprecating-formatting-rules/

我现在正在使用您的eslint格式化代码方案，如果后面不再好用的话，我该提前考虑使用prettier来进行代码格式化了

**Comment by antfu** [comment]
https://eslint.style/
