### ISSUE TITLE
无法关掉 antfu/top-level-function 规则

### ISSUE THREAD

**Issue by duanshoujian** [antfu/eslint-config#436]
### Describe the bug

export default antfu(
  {
    rules: {
      'style/no-tabs': 'off',
      'antfu/top-level-function': 'off',
    },
    ignores: ['pnpm-lock.yaml', 'auto-imports.d.ts', 'components.d.ts', '.gitignore', 'public', '**/AlimamaDongFangDaKai-Regular-normal.js'],
  },
  {
    ignores: ['**/services/*', '**/services/*.ts'],
    files: ['**/*.?([cm])ts', '**/*.?([cm])tsx'],
    languageOptions: {
      parser: parserTypeScript,
      parserOptions: {
        sourceType: 'module',
      },
    },
    plugins: {
      '@typescript-eslint': pluginTypeScript,
    },
    rules: {
      ...pluginTypeScript.configs.strict.rules,
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/member-delimiter-style': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      'style/member-delimiter-style': 'off',
      '@typescript-eslint/no-import-type-side-effects': 'error',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { disallowTypeAnnotations: false, fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/prefer-literal-enum-member': ['error', { allowBitwiseExpressions: true }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
    },
  },
  {
    files: ['**/*.vue'],
    plugins: {
      'rulesdir': rulesDirPlugin,
      'vue': pluginVue,
      '@typescript-eslint': pluginTypeScript,
    },
    processor: pluginVue.processors['.vue'],
    languageOptions: {
      parser: parserVue,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
        extraFileExtensions: ['.vue'],
        parser: parserTypeScript,
        sourceType: 'module',
      },
    },
    rules: {
      'no-undef': 'off',
      'rulesdir/text-import': 'error',
      'antfu/top-level-function': 'off',
      'no-unused-vars': 'off',
      'vue/no-v-html': 'off',
      'vue/require-default-prop': 'off',
      'vue/require-explicit-emits': 'off',
      'vue/multi-word-component-names': 'off',
      'vue/no-setup-props-reactivity-loss': 'off',
      'vue/component-name-in-template-casing': ['off'],
      '@typescript-eslint/no-explicit-any': 'warn',
      'style/member-delimiter-style': 'off',
    },
  },
  unocss.configs.flat,
)

### Reproduction

xx

### System Info

```Shell
xx
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by duanshoujian** [comment]
注意到导入的配置中
![image](https://github.com/antfu/eslint-config/assets/52518325/ecbf9f61-d2b1-40e3-b429-844579f70881)
仍有error的规则，如何去关掉呢

**Comment by Bernankez** [comment]
```ts
import antfu from "@antfu/eslint-config";

export default antfu({
  stylistic: {
    overrides: {
      "antfu/top-level-function": "off",
    },
  },
});
```
