### ISSUE TITLE
`v2.9.1` have a peer-dependency of `eslint-plugin-svelte@^2.36.0-0`, which is not released yet

### ISSUE THREAD

**Issue by CNSeniorious000** [antfu/eslint-config#437]
### Describe the bug

`v2.9.0` works well, but when I updated to `v2.9.1`+ the minimal version of `eslint-plugin-svelte` changed to `^2.36.0-0`. But for now the latest version is `^2.35.1`

This make sveltekit application on vercel and netlify deployments fail

Try the following reproduction by install dependencies and then `pnpm eslint .`, it will automatically install `eslint-plugin-svelte` but raising a peer-dependency warning

### Reproduction

https://stackblitz.com/edit/vitejs-vite-g1tdbd?file=package.json

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
    Memory: 1.96 GB / 15.18 GB
  Binaries:
    Node: 20.9.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 10.1.0 - D:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.5 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.53)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
We could revert it to the latest stable version, PR welcome :)

**Comment by CNSeniorious000** [comment]
OK, then should the version field be `2.9.2` or just `2.11.4`?
