### ISSUE TITLE
Conflict with @stylistic/indent and @stylistic/jsx-indent

### ISSUE THREAD

**Issue by yunsii** [antfu/eslint-config#440]
### Describe the bug

An error will be reported anyway
![image](https://github.com/antfu/eslint-config/assets/18096089/c47a4ea8-cdb4-46a7-be4b-e4afcd2ef928)

### Reproduction

https://github.com/yunsii/stylistic-repro/blob/master/src/index.tsx

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 11.29 GB / 15.52 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.19.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.11.0 - ~/.nvm/versions/node/v18.19.0/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I don't use JSX myself, thus I won't have enough incentive to work on it any sooner. Pr welcome if anyone want to investigate and find a solution

**Comment by yunsii** [comment]
Upstream issue: https://github.com/eslint-stylistic/eslint-stylistic/issues/312
