### ISSUE TITLE
`'vue/require-explicit-emits'` is enabled in Vue 2

### ISSUE THREAD

**Issue by cloydlau** [antfu/eslint-config#443]
### Describe the bug

`'vue/require-explicit-emits'` is a rule for Vue 3 only.

### Reproduction

https://github.com/cloydlau/reproduction.git

### System Info

```Shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M2
    Memory: 68.14 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.0 - ~/Library/pnpm/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
    pnpm: 8.15.6 - ~/Library/pnpm/pnpm
    bun: 0.5.9 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 123.0.6312.107
    Safari: 17.3.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
PR welcome to fix it. Thanks
