### ISSUE TITLE
Introduce `eslint-react`

### ISSUE THREAD

**Issue by hyoban** [antfu/eslint-config#452]
### Clear and concise description of the problem

- https://github.com/rel1cx/eslint-react
- https://twitter.com/isukkaw/status/1715793822205243743
- https://eslint-react.xyz/docs/faq

I am willing to submit a pull request for this change.

### Suggested solution

Maybe provide an option to use `eslint-react` or `eslint-plugin-react`? So that this will not be a breaking change.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I don't mind switching. I do notice that eslint-plugin-react doesn't seems to work on ESLint v9 - PR welcome :)
