### ISSUE TITLE
Stricter ordering of imports

### ISSUE THREAD

**Issue by hyoban** [antfu/eslint-config#456]
### Clear and concise description of the problem

In some cases, users may cause the ordering of imports to change, either through manual adjustment or the editor's `Organize imports` feature. The current sorting rules `import/order` and `sort-imports` are not enough to unify the sorting style, which is unstable for git diff.

I am willing to submit a pull request for this change.

### Suggested solution

Bring in [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort).

### Additional context

- [Difference with import/order](https://github.com/lydell/eslint-plugin-simple-import-sort#how-is-this-rule-different-from-importorder)
- [Is sorting imports/exports safe?](https://github.com/lydell/eslint-plugin-simple-import-sort#is-sorting-importsexports-safe)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
Thanks for the reminder. This should also be an option. There is no need to introduce additional plug-ins now.

**Comment by antfu** [comment]
Would you share some examples of the result of reach rule? To me, the current state seems to work fine.

**Comment by thenbe** [comment]
> the current state seems to work fine.

I don't quite remember the details, but there were scenarios where the vanilla sort rules would not handle, whereas the alternative rules from perfectionist was able to handle.

It's been a while, but I think this was my main issue with it: https://github.com/import-js/eslint-plugin-import/issues/1787

**Comment by hyoban** [comment]
Close as it may not be a good idea. If you want it, you can try to use [eslint-plugin-perfectionist](https://github.com/azat-io/eslint-plugin-perfectionist) or [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort).

Example of how to use eslint-plugin-simple-import-sort:

```js
import antfu from '@antfu/eslint-config'
import simpleImportSort from 'eslint-plugin-simple-import-sort'

export default antfu(
  {},
  {
    plugins: {
      'simple-import-sort': simpleImportSort,
    },
    rules: {
      'import/order': 'off',
      'sort-imports': 'off',
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',
    },
  },
)
```

**Comment by JohnCampionJr** [comment]
Hoping maybe this will help someone out who like me wants to use perfectionist but didn't understand why the above config didn't do much.  The default perfectionist sort-imports doesn't define any groups.  So my config pulls in the rules from the natural sort config.

https://gist.github.com/JohnCampionJr/a082f8967dd6341c41d923ad8502e999

**Comment by JohnCampionJr** [comment]
@antfu Would you be amenable to a PR adding an option to enable import sorting by perfectionist?

Basically make this available by option (could be set to alpha, natural or line length) per perfectionist settings
```
rules: {
      'import/order': 'off', // handled by perfectionist
      'sort-imports': 'off', // handled by perfectionist
      'perfectionist/sort-imports': perfectionistNatural.rules['perfectionist/sort-imports'],
      'perfectionist/sort-exports': perfectionistNatural.rules['perfectionist/sort-exports'],
      'perfectionist/sort-named-imports': perfectionistNatural.rules['perfectionist/sort-named-imports'],
      'perfectionist/sort-named-exports': perfectionistNatural.rules['perfectionist/sort-named-exports'],
    },
```

**Comment by mefengl** [comment]
@JohnCampionJr 

My approach is to install perfectionist separately and then use its recommend rules like this:

```js
import antfu from '@antfu/eslint-config'
import perfectionist from 'eslint-plugin-perfectionist'

export default antfu(
  // perfectionist
  {
    rules: {
      'import/order': 'off',
      ...perfectionist.configs['recommended-natural'].rules,
    },
  },
)
```
