### ISSUE TITLE
XML formatter

### ISSUE THREAD

**Issue by zanfee** [antfu/eslint-config#460]
### Clear and concise description of the problem

As a [SAPUI5](https://sapui5.hana.ondemand.com/sdk/#/) (a JavaScript framework) developer I define views (based on the MVC pattern) for my web apps using XML (as described in the [SAPUI5 docs](https://sapui5.hana.ondemand.com/sdk/#/topic/91f292806f4d1014b6dd926db0e91070.html)). Currently I use [a fork of @antfu/eslint-config](https://github.com/zanfee/eslint-config) which includes the [@html-eslint](https://github.com/yeonjuan/html-eslint) plugin and parser that work for both HTML and XML. I created this fork before you included formatters in @antfu/eslint-config and I think that I could migrate back to @antfu/eslint-config once XML is supported. Since XML is a common format for many use-cases, I believe that it would benefit other developers too.

I'd be happy to submit a PR for this.

### Suggested solution

I think we could use [eslint-plugin-format](https://github.com/antfu/eslint-plugin-format) based on Prettier and dprint to support XML as you already do for HTML. I haven't checked if there's anything else you need to do to make it work, but I'd be happy to give it a try.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zanfee** [comment]
Prettier does not support XML by default but with a community plugin ([plugin-xml](https://github.com/prettier/plugin-xml)).

**Comment by zanfee** [comment]
There's no XML plugin listed on [dprint's plugin site](https://dprint.dev/plugins/) and I couldn't find one either. Are you suggesting creating a plugin for XML from scratch? Dprint also has a [Prettier wrapper](https://github.com/dprint/dprint-plugin-prettier), but since [eslint-plugin-format](https://github.com/antfu/eslint-plugin-format) supports both Prettier and dprint, there's probably no point in using that but rather just Prettier with the community plugin. But I'm not familiar with dprint, so maybe you know more than I do and could elaborate.

Having XML support as opt-in is fine for me.

**Comment by antfu** [comment]
Oh, I thought Dprint had it built in. I am fine with Prettier, but the problem I see is because XML support is provided as an external plugin which would make the configuration tricky - If you managed to get it work, we could then discuss it with in the PR.
