### ISSUE TITLE
OptionsConfig.autoRenamePlugins 配置设置为 false 似乎不生效

### ISSUE THREAD

**Issue by bbye913** [antfu/eslint-config#466]
### Describe the bug

<img width="552" alt="image" src="https://github.com/antfu/eslint-config/assets/11909694/b32c433f-9d77-461a-83ee-bab786ae7b28">

### Reproduction

具体代码如上图，日志打出的插件还是自动重命名为预设默认值

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 35.82 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.0.6 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.94
    Edge: 124.0.2478.67
    Safari: 17.4.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Because the rules are already written that way, `autoRenamePlugin` is an option to convert rules from outside (userland) to match the convention. This is working as expected
