### ISSUE TITLE
[Nuxt] Error: Key "plugins": Cannot redefine plugin "import".

### ISSUE THREAD

**Issue by onmax** [antfu/eslint-config#473]
### Describe the bug

Running `eslint` results in an error. I tried to follow the [manual](https://eslint.nuxt.com/packages/module) but got this error:

<details><summary>Error</summary>
<p>

```bash
maxi@maxi:~/personal/eslint-reproduction-bug$ nr lint:fix

> nuxt-app@ lint:fix /home/maxi/personal/eslint-reproduction-bug
> eslint . --fix


Oops! Something went wrong! :(

ESLint: 9.2.0

ConfigError: Config "antfu/imports/rules": Key "plugins": Cannot redefine plugin "import".
    at rethrowConfigError (/home/maxi/personal/eslint-reproduction-bug/node_modules/.pnpm/@humanwhocodes+config-array@0.13.0/node_modules/@humanwhocodes/config-array/api.js:230:8)
    at /home/maxi/personal/eslint-reproduction-bug/node_modules/.pnpm/@humanwhocodes+config-array@0.13.0/node_modules/@humanwhocodes/config-array/api.js:1032:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfig (/home/maxi/personal/eslint-reproduction-bug/node_modules/.pnpm/@humanwhocodes+config-array@0.13.0/node_modules/@humanwhocodes/config-array/api.js:1028:39)
    at FlatConfigArray.isFileIgnored (/home/maxi/personal/eslint-reproduction-bug/node_modules/.pnpm/@humanwhocodes+config-array@0.13.0/node_modules/@humanwhocodes/config-array/api.js:1060:15)
    at /home/maxi/personal/eslint-reproduction-bug/node_modules/.pnpm/eslint@9.2.0/node_modules/eslint/lib/eslint/eslint-helpers.js:346:57
    at Array.reduce (<anonymous>)
    at /home/maxi/personal/eslint-reproduction-bug/node_modules/.pnpm/eslint@9.2.0/node_modules/eslint/lib/eslint/eslint-helpers.js:333:36
    at /home/maxi/personal/eslint-reproduction-bug/node_modules/.pnpm/eslint@9.2.0/node_modules/eslint/lib/eslint/eslint-helpers.js:296:32
    at Object.isAppliedFilter (/home/maxi/personal/eslint-reproduction-bug/node_modules/.pnpm/@nodelib+fs.walk@1.2.8/node_modules/@nodelib/fs.walk/out/readers/common.js:12:31)
 ELIFECYCLE  Command failed with exit code 2.
```

</p>
</details> 

It's probably a misconfiguration or I've missed something, but after re-reading everything I've been unable to find where the fault lies. Thanks in advance for your reply!

## Steps

1. pnpm dlx nuxi@latest init eslint-reproduction-bug
2. `cd eslint-reproduction-bug/` 3.
3. `pnpm install`.
4. `pnpm run dev`.
5. Using the Nuxt DevTools, I installed the ['Eslint Module'](https://eslint.nuxt.com/)
6. Manually install `eslint` with `pnpm i eslint` (as explained in the [manual](https://eslint.nuxt.com/packages/module). I was expecting it to be installed automatically from the DevTools).
7. In the newly created `eslint.config.mjs` add the [`@antfu/eslint-config`](https://github.com/onmax/eslint-reproduction-bug/blob/main/eslint.config.mjs) config.
8. Update the `eslint` config in `nuxt.config.ts`.
9. Add `lint` and `lint:fix` to package.json
10. Run `lint:fix`. It will also ask for the extra `eslint` configuration I installed (`"@unocss/eslint-plugin"` and `"eslint-plugin-format"`).
11. The error will be shown

### Reproduction

https://github.com/onmax/eslint-reproduction-bug

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 1.35 GB / 7.45 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.5 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 9.1.0 - ~/.local/share/pnpm/pnpm
    bun: 1.0.20 - ~/.nvm/versions/node/v20.10.0/bin/bun
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
You should set `standalone` to `false`

**Comment by onmax** [comment]
Hey, I have update the repro with `standalone` to `false`, but it still happening

![image](https://github.com/antfu/eslint-config/assets/22072217/f9bab76e-ec5a-4408-8960-e11d4e927a8a)

**Comment by yimme** [comment]
Ran into the same issue @onmax. running the nuxt app first with `npm run dev` fixed it for me.

**Comment by onmax** [comment]
Awesome thank you!

Now it seems to work, but now I get a weird eslint error:

```
maxi@maxi:~/personal/eslint-reproduction-bug$ nr lint:fix

> nuxt-app@ lint:fix /home/maxi/personal/eslint-reproduction-bug
> eslint . --fix


/home/maxi/personal/eslint-reproduction-bug/components/WelcomeItem.vue
  2:33  error  Parsing error: Unexpected token )

✖ 1 problem (1 error, 0 warnings)

 ELIFECYCLE  Command failed with exit code 1.
```

<details><summary><code>WelcomeItem.vue</code></summary>
<p>

```vue
<script setup lang="ts">
defineProps<{ heading: string }>()
</script>

<template>
    <h3 >
    {{heading}}
    </h3>
</template>
```

</p>
</details> 


## Steps to reproduce:

1. Clone `[onmax/eslint-reproduction-bug](https://github.com/onmax/eslint-reproduction-bug)`
2. Run `pnpm install` and `pnpm dev`
3. Kill server
4. Run `pnpm lint:fix` or `pnpm lint`

Did I misconfigured something? It is valid Vue as it is working as expected. Thank you for your response 😃
