### ISSUE TITLE
Tailwind support

### ISSUE THREAD

**Issue by oumarbarry** [antfu/eslint-config#483]
### Clear and concise description of the problem

I would greatly appreciate Tailwind support, if feasible.

In my projects, I frequently utilize [eslint-stylistic](https://github.com/eslint-stylistic/eslint-stylistic).
At present, the primary factor that would motivate me to continue using Prettier is [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss).

Notably, UnoCSS already offers this feature through [@unocss/eslint-config](https://github.com/unocss/unocss/tree/main/packages/eslint-config).

I use Nuxt UI, which requires Tailwind, so it would be nice to have Tailwind supported here.

### Suggested solution

Integrating [eslint-plugin-tailwindcss](https://github.com/francoismassart/eslint-plugin-tailwindcss)

or 

not sure about that, maybe making [@unocss/eslint-config](https://github.com/unocss/unocss/tree/main/packages/eslint-config) agnostic

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks for bringing this up, but sorry, I have no interest in having Tailwind built in. It shouldn't be hard to extend the rule on userland.
