### ISSUE TITLE
How to setup with nuxt and stylistics

### ISSUE THREAD

**Issue by csntr** [antfu/eslint-config#485]
I am trying to setup a project without prettier. If I just create a nuxt app and my nuxt config looks like:

```
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['@nuxt/eslint'],
  eslint: {
    config: {
      stylistic: true,
    },
  },
})
```

Then stylistics works fine I can just save and everything gets formatted.

Then I add this config by adding this to my `eslint.config.js`:

```
import antfu from '@antfu/eslint-config'
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  antfu(),
)
```

And stylistics stop working. I tried removing the eslint config part from nuxt config and going with something like:

```
import antfu from '@antfu/eslint-config'
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  antfu({
    stylistic: true
  }),
)
```

But no success so far. Any tips for me how to get this working properly?

**Comment by Dimava** [comment]
Try #482 , could help

**Comment by csntr** [comment]
I tired that and did not work nuxt config became:

```
  eslint: {
    checker: {
            configType: 'flat',
    },
    config: {
      standalone: false,
      stylistic: true
    }
  },
```

eslint config:

```
export default withNuxt(antfu({stylistic: true}))
```

**Comment by onmax** [comment]
I am also having problems with Nuxt Eslint: https://github.com/antfu/eslint-config/issues/473#issuecomment-2118764429

**Comment by csntr** [comment]
As now everything is getting formatted as I want it I am closing this, thank you!
