### ISSUE TITLE
Failed to format vue file.

### ISSUE THREAD

**Issue by coderwyd** [antfu/eslint-config#488]
### Describe the bug

Automatic repair using eslint in vscode failed.
![image](https://github.com/antfu/eslint-config/assets/53386850/a44ee65f-fb6e-418a-94eb-6f00ac22fb7f)
![image](https://github.com/antfu/eslint-config/assets/53386850/eca67e77-24ad-48c1-9567-657cd9f5fe5f)

### Reproduction

https://github.com/coderwyd/eslint-vue-format-repo

### Eslint Version
    "eslint": "^9.3.0",
    "eslint-plugin-format": "^0.1.1",
    "@antfu/eslint-config": "^2.19.0",
    "@unocss/eslint-plugin": "^0.60.3",
    "vue": "^3.4.27",

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 3.30 GB / 15.72 GB
  Binaries:
    Node: 20.13.1 - ~\AppData\Local\Volta\tools\image\node\20.13.1\node.EXE
    npm: 10.5.2 - ~\AppData\Local\Volta\tools\image\node\20.13.1\npm.CMD
    pnpm: 9.1.2 - ~\AppData\Local\Volta\tools\image\pnpm\9.1.2\bin\pnpm.CMD
    bun: 1.1.0 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by coderwyd** [comment]
Sorry, I overlooked this. I've added minimal reproductions.

**Comment by lwm98** [comment]
eslint config 那里要显示开启vue文件format（css如需也要），具体readme文件中有[readme](https://github.com/antfu/eslint-config?tab=readme-ov-file#rules-overrides)

**Comment by Eden-Sun** [comment]
It works well if removing the tab
<img width="457" alt="截圖 2024-05-29 上午9 31 12" src="https://github.com/antfu/eslint-config/assets/10295125/a2bd0e4f-7098-4c3e-8d90-97ba7a9f1183">
<img width="479" alt="截圖 2024-05-29 上午9 32 36" src="https://github.com/antfu/eslint-config/assets/10295125/67053713-bbb9-4381-a53c-db0a5326a6c3">

**Comment by coderwyd** [comment]
Damn, I didn't notice the label and when I took it off I realized he worked just fine, thank you!
