### ISSUE TITLE
react tsConfigPath is always undefined

### ISSUE THREAD

**Issue by tinchoz49** [antfu/eslint-config#489]
### Describe the bug

Using `getOverride` returns only the override rules so `tsConfigPath` is never going to be defined there. 

line: https://github.com/antfu/eslint-config/blob/0e301193b77384d2482af1bbbb89d9de7084be6f/src/factory.ts#L185C7-L185C70

### Reproduction

You can check with a console.log in that line and try to setup a tsConfigPath in the settings.

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 281.33 MB / 32.00 GB
    Shell: Unknown
  Binaries:
    Node: 20.13.1 - ~/Library/Caches/fnm_multishells/85923_1716830984969/bin/node
    npm: 10.5.2 - ~/Library/Caches/fnm_multishells/85923_1716830984969/bin/npm
  Browsers:
    Brave Browser: 125.1.66.115
    Chrome: 117.0.5938.149
    Safari: 17.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [x] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
PR welcome
