### ISSUE TITLE
Comments are removed by `tsup`

### ISSUE THREAD

**Issue by pauliesnug** [antfu/eslint-config#496]
### Describe the bug

When the package is built, all comments including descriptions of features and rules, as well as documentation/jsdoc of the `antfu` factory are stripped. This impacts the ability to configure the config, but also reduces package size. Is this intentional?

### Reproduction

Install `@antfu/eslint-config` and look at the typings in hover menu.

### System Info

```Shell
n/a
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by thenbe** [comment]
The distributed files still include the jsdoc style comments in the `dist/index.d.ts` file, no? That's what my editor is using to provide intellisense when I hover or autocomplete I start typing.

Are you seeing something different? I'm on `v2.20.0`.

**Comment by pauliesnug** [comment]
> The distributed files still include the jsdoc style comments in the `dist/index.d.ts` file, no? That's what my editor is using to provide intellisense for the `@antfu/eslint-config` package when I hover or autocomplete when I start typing.
> 
> Are you seeing something different? I'm on `v2.20.0`.

Hmm... I also see them in the `dist/index.d.ts`, but for some reason VSCode isn't adding inlay hints from them.
