### ISSUE TITLE
如何添加没有预设的插件，如 eslint-config-taro

### ISSUE THREAD

**Issue by topazur** [antfu/eslint-config#512]
### Clear and concise description of the problem

eslint-config-taro

### Suggested solution

增加选项以添加未预设的插件

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Please read the docs of ESLint or the plugin. Issue is not for asking questions. Thanks.
