### ISSUE TITLE
请问可以新增 globals key 吗？小程序开发会全局注入 uni、wx 等变量

### ISSUE THREAD

**Issue by sunpm** [antfu/eslint-config#513]
### Clear and concise description of the problem

小程序编译后会全局注入 uni、wx 等变量，可以保证它们一定存在。
但是开发过程中没有注入，导致 eslint 检测报错。
原来 `.eslintrc.js中 ` 可以配置 globals，配置到 `eslint.config.js` 出现异常：`Error: Key "globals": This appears to be in eslintrc format rather than flat config format.`

### Suggested solution

可否在 eslint config 中增加 globals 配置属性

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
不是可以类型里面声明一个全局的变量吗，就像window

**Comment by sunpm** [comment]
是的，如果使用tsconfig不会有这个问题，但是用的是js…

**Comment by antfu** [comment]
你可以自己配置。我不用小程序，没有兴趣支持

**Comment by Azir-11** [comment]
给后来者提供一点帮助，可以这样配置以支持全局key：
```
const antfu = require('@antfu/eslint-config').default
const { FlatCompat } = require('@eslint/eslintrc')

const compat = new FlatCompat()

module.exports = antfu({
// your config
}, 
...compat.config({
  globals: {
    wx: 'readonly', // 微信小程序
    uni: 'readonly', // uniapp
  },
}))
```
FlatCompat 的配置看你的项目是ES的还是Common的，我这个给的是common的，ES的直接把require换成import就好了
