### ISSUE TITLE
unmet peer eslint@^8.56.0: found 9.5.0

### ISSUE THREAD

**Issue by liu-xinhui** [antfu/eslint-config#518]
### Describe the bug

 WARN  Issues with peer dependencies found
.
└─┬ @antfu/eslint-config 2.21.1
  ├─┬ @stylistic/eslint-plugin 2.3.0
  │ └─┬ @stylistic/eslint-plugin-plus 2.3.0
  │   └─┬ @typescript-eslint/utils 7.14.1
  │     └── ✕ unmet peer eslint@^8.56.0: found 9.5.0
  ├─┬ @typescript-eslint/eslint-plugin 7.14.1
  │ ├── ✕ unmet peer eslint@^8.56.0: found 9.5.0
  │ └─┬ @typescript-eslint/type-utils 7.14.1
  │   └── ✕ unmet peer eslint@^8.56.0: found 9.5.0
  ├─┬ @typescript-eslint/parser 7.14.1
  │ └── ✕ unmet peer eslint@^8.56.0: found 9.5.0
  └─┬ eslint-plugin-unused-imports 3.2.0
    └── ✕ unmet peer eslint@8: found 9.5.0

### Reproduction

unmet peer eslint@^8.56.0: found 9.5.0

### System Info

```Shell
 WARN  Issues with peer dependencies found
.
└─┬ @antfu/eslint-config 2.21.1
  ├─┬ @stylistic/eslint-plugin 2.3.0
  │ └─┬ @stylistic/eslint-plugin-plus 2.3.0
  │   └─┬ @typescript-eslint/utils 7.14.1
  │     └── ✕ unmet peer eslint@^8.56.0: found 9.5.0
  ├─┬ @typescript-eslint/eslint-plugin 7.14.1
  │ ├── ✕ unmet peer eslint@^8.56.0: found 9.5.0
  │ └─┬ @typescript-eslint/type-utils 7.14.1
  │   └── ✕ unmet peer eslint@^8.56.0: found 9.5.0
  ├─┬ @typescript-eslint/parser 7.14.1
  │ └── ✕ unmet peer eslint@^8.56.0: found 9.5.0
  └─┬ eslint-plugin-unused-imports 3.2.0
    └── ✕ unmet peer eslint@8: found 9.5.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Dimava** [comment]
Upstream bug I guess
https://github.com/typescript-eslint/typescript-eslint/pull/9413

**Comment by shimarulin** [comment]
Workaround:

Add to `package.json`:

```
  "pnpm": {
    "peerDependencyRules": {
      "allowedVersions": {
        "eslint": "9"
      }
    }
  }
```

**Comment by gt-packages** [comment]
Works better with 2.22.0.beta.3.
But still one dependency issue with eslint-plugin-import-x:

![2024-07-08_16-44-21](https://github.com/antfu/eslint-config/assets/172611317/d610b522-0a08-49b6-bd56-0871c8622c06)

**Comment by michael-hillmann** [comment]
After updating to 2.22.0, I got the similar issue:
![image](https://github.com/antfu/eslint-config/assets/16838325/13b549d0-22c8-46e7-ab2e-4abdfc50e50a)

**Comment by GaborTorma** [comment]
same issue with eslint 9

**Comment by GaborTorma** [comment]
eslint-plugin-import-x has new version with eslint 9 support.

**Comment by Dimava** [comment]
Was this resolved in https://github.com/antfu/eslint-config/commit/794424466eb10d88de1e060bad23f6416703e943 ?
If not, what does remain?

**Comment by michael-hillmann** [comment]
in my case, it's working 👍

**Comment by paker777** [comment]
> There is nothing we can do on our side but wait for the ecosystem, unfortunately. You you either enforce the version with overrides, or ignore the warning.

We'll just have to ignore it.

**Comment by CCProHu** [comment]
`eslint-plugin-import-x` still use `typescript-eslint/utils` 7.16.1
![2024-07-19_14-59-28](https://github.com/user-attachments/assets/726ece53-54de-408a-a80d-79f41e7d1715)

**Comment by GaborTorma** [comment]
Only eslint-pluin-import-x still remain. [SukkaW](https://github.com/SukkaW) says tring to [backport](https://github.com/un-ts/eslint-plugin-import-x/pull/112#issuecomment-2264466503) to [import-js/eslint-plugin-import](https://github.com/import-js/eslint-plugin-import/pull/3018).
What do you think, we would able to use it?

In the meantime @anfu/eslint-config safe to use with eslint 9?
