### ISSUE TITLE
Docs: switching from 'ts/' prefix to '@typescript-eslint/'

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [antfu/eslint-config#527]
### Describe the bug

Right now, this _(very thoroughly crafted, nicely done!)_ ESLint config uses the prefix `'ts/'` for [typescript-eslint](https://typescript-eslint.io) rules per https://github.com/antfu/eslint-config?tab=readme-ov-file#plugins-renaming. That means users configure rules like:

```ts
{
  'ts/array-type': 'error',
}
```

However, the [recommended preset configs from typescript-eslint](https://typescript-eslint.io/users/configs) use a `'@typescript-eslint/'` prefix, not `'ts/'`. A lot of projects are accustomed to using the '`@typescript-eslint/'` prefix. And if folks ever want to combine a typescript-eslint shared config with antfu/eslint-config, they have mismatched prefixes.

It took me a bit of wrestling, but this seems to be working to get those prefixes moved over:

```js
import antfu from "@antfu/eslint-config";

export default antfu()
  .renamePlugins({
    ts: "@typescript-eslint",
  })
  .overrideRules({
    // (example)
    "@typescript-eslint/no-array-constructor": "error",
  });
``` 

So, two docs questions:

* Confirmation: is this the right way to do that?
* Do you think it'd be reasonable to mention this anywhere in docs?

Longer-term, I'd be interested in seeing if there's a good way to use typescript-eslint's stricter configs on top of the antfu/eslint-config starter...

### Miscellaneous Context

I realize the `ts/` prefix is _much easier_ to read+write than the super verbose `@typescript-eslint/`. But we're stuck with `@typescript-eslint/` in typescript-eslint because that's what everyone's been using for years. 

We in typescript-eslint have previously surfaced feedback to ESLint core that prefix duplication is a known user pain: https://github.com/eslint/eslint/discussions/17766. But there isn't a way to lock down and/or deduplicate the prefixes (yet?).

### Reproduction

https://github.com/JoshuaKGoldberg/repros/tree/antfu-eslint-config-typescript-eslint-prefix

### System Info

```Shell
n/a
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
Hey, thanks for the issue! I knew it coming 🤣

I wrote this part: https://github.com/antfu/eslint-config#plugins-renaming; I bet you might have already read it. I am super sorry if my move caused some fragmentation to `@typescript-eslint`'s community, but on the other hand, I care about the end-user experience more. In a way I kind of ambitiously position this configuration as "Anthony's Favored ESLint" or even "Anthony's Favored Linter", where the plugins' package names are kind of, implementation details. I wanted to give an answer to "ESLint is too complicated to config" as "It can be simple as Prettier, that is all-in-one & out-of-box" for 90% of the cases.

In terms of configs interop, I made `eslint-flat-config-utils` ([`renamePlugins`](https://github.com/antfu/eslint-flat-config-utils/blob/main/src/rename.ts) which you also aware, and set the opposite renaming in this config as

https://github.com/antfu/eslint-config/blob/3f3e3f4515cc12f3b2109b413ac48274896fcb6e/src/factory.ts#L64

This means if you plug a shared config from `@typescript-eslint`, it will still work for users as `ts/` - in a way it is consistent within the context of this config.

Again, I am sorry. But also, I would not consider moving it back. I know what it means to the ecosystem fragmentation, but on the other hand, I think you couldn't prevent the community from doing what they could do (that's how open source community work; in other words - even if I revert, there will still be a lot of people do). But in the meantime, I am super willing to communicate more, provide more context, help with tooling, or in any form to help you and the community move to a more robust solution/convention, etc, for such a voice to exist, while still having a strong community.

Are you suggesting we add a doc to tell the user "how to change the renaming back"? In a way I am up to it, but I think I would also mention that "I wouldn't recommend doing it with my config in paticular" - if that's ok to you, I would go ahead and do it.

Either way, let's talk more, so we could understand each others position more and potentially find a better mid-ground. Thanks!

**Comment by JoshuaKGoldberg** [comment]
Haha I'm glad this wasn't a surprise! To be honest, I think I'd made a mental note to file this soon after flat config stabilized, then forgot about it...

> Are you suggesting we add a doc to tell the user "how to change the renaming back"? In a way I am up to it, but I think I would also mention that "I wouldn't recommend doing it with my config in paticular" 

Yes, exactly. I don't intend in this issue to contest or push back against what you're doing. I'm certainly not asking to change back. I just wanted to confirm the right way to use `@antfu/eslint-config` with typescript-eslint rules prefixed as `'@typescript-eslint/'`. 🙂 

> - if that's ok to you, I would go ahead and do it.

Just to confirm - are you saying I should send a PR for this?
