### ISSUE TITLE
ignored files still get checked

### ISSUE THREAD

**Issue by CNSeniorious000** [antfu/eslint-config#530]
### Describe the bug

If you use `eslint<9` with latest stable `@antfu/eslint-config`, it will fail to ignore the files specified in `.gitignore`. I've fired the same problem here in https://github.com/antfu/eslint-config-flat-gitignore/issues/11. Sorry for reporting this twice.

In the following stackblitz project, I've locked `eslint-config-flat-gitignore` to be `0.1.5` so no check fails. But if you remove that, delete the lockfile and then reinstall, checks will fail in an ignored file.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ruwbf2?file=package.json

### System Info

```Shell
System:
    OS: Linux 5.4 OpenCloudOS 8.8
    CPU: (2) x64 Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
    Memory: 1.60 GB / 3.58 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 18.16.0 - /usr/bin/node
    Yarn: 1.22.22 - ~/.local/share/pnpm/yarn
    npm: 10.8.1 - ~/.local/share/pnpm/npm
    pnpm: 9.4.0 - ~/.local/share/pnpm/pnpm
    bun: 1.1.17 - ~/.bun/bin/bun
```

### Used Package Manager

bun

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by xsjcTony** [comment]
Ping `eslint-config-flat-gitignore` to `v0.1.5` will do the job, until you upgrade ESLint to 9

**Comment by CNSeniorious000** [comment]
Thanks! But `@antfu/eslint-config` is markded to work with `"eslint": ">=8.40.0"`. So maybe at least one of these two places needs to be changed?

**Comment by CNSeniorious000** [comment]
Thank you very much for https://github.com/antfu/eslint-config-flat-gitignore/releases/tag/v0.1.7 ! Also apologize for causing you some wasted time.
