### ISSUE TITLE
Reduce visible severity of all Autofixable rules

### ISSUE THREAD

**Issue by Dimava** [antfu/eslint-config#532]
### Clear and concise description of the problem

For most of autofixable rules you don't consider them errors (in edit time) - as they will be autofixed anyway
But they are red, and that's annoying

### Suggested solution

https://github.com/microsoft/vscode-eslint/pull/1841
You can change the severity of a eslint rule based on its autofixability
```json
"eslint.rules.customizations": [
    { "rule": "*", "fixable": true, "severity": "info" }
  ]
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Dimava** [comment]
I have personally set then to cyan "info"

**Comment by antfu** [comment]
I personally feel that for non-formatting rules, it's still better for me to know the error and understand why my code is changed. In the end, it's in users local settings. I think we did the job of showcasing the capability of doing this, and it's up to users to modify it to what they want. Thanks for bringing this up.
