### ISSUE TITLE
markdown style/no-tabs cann't disable

### ISSUE THREAD

**Issue by chenglu4343** [antfu/eslint-config#534]
### Describe the bug

markdown style/no-tabs cann't disable

```js
import antfu from '@antfu/eslint-config'

export default antfu({
  markdown: {
    overrides: {
      'style/no-tabs': 'off',
    },
  },
})
```

eslint will still report errors when using tab in markdown

```text
  2:1  error  Unexpected tab character  style/no-tabs
  3:1  error  Unexpected tab character  style/no-tabs
```

### Reproduction

https://github.com/chenglu4343/try-eslint

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400
    Memory: 2.62 GB / 15.78 GB
  Binaries:
    Node: 18.20.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.6 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.61)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
Use `export default antfu().removeRules('style/no-tabs')` to remove all occurrences if you don't need that rule at all.
