### ISSUE TITLE
No matching version found for @typescript-eslint/eslint-plugin@8

### ISSUE THREAD

**Issue by Byron2016** [antfu/eslint-config#539]
### Describe the bug

It was not possible to instal V.2.22.2.
![errorFu](https://github.com/user-attachments/assets/e727acee-fc1c-4160-b687-7cdcde18ab07)

### Reproduction

npx @antfu/eslint-config@latest

### System Info

```Shell
Windows 10
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by mcfarljw** [comment]
I'm having this same issue as well so I'm stuck on `@antfu/eslint-config@2.21.3` using `npm@10.8.2`. Here is a copy of the error from the log:

```
311 verbose type range
312 verbose stack @typescript-eslint/eslint-plugin: No matching version found for @typescript-eslint/eslint-plugin@8.
312 verbose stack     at module.exports (/Users/joshua/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:215:23)
312 verbose stack     at RegistryFetcher.manifest (/Users/joshua/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:130:54)
312 verbose stack     at async #fetchManifest (/Users/joshua/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1199:20)
312 verbose stack     at async #nodeFromEdge (/Users/joshua/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1037:19)
312 verbose stack     at async #buildDepStep (/Users/joshua/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:901:11)
312 verbose stack     at async Arborist.buildIdealTree (/Users/joshua/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
312 verbose stack     at async Promise.all (index 1)
312 verbose stack     at async Arborist.reify (/Users/joshua/.nvm/versions/node/v20.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
312 verbose stack     at async Install.exec (/Users/joshua/.nvm/versions/node/v20.15.0/lib/node_modules/npm/lib/commands/install.js:150:5)
312 verbose stack     at async Npm.exec (/Users/joshua/.nvm/versions/node/v20.15.0/lib/node_modules/npm/lib/npm.js:207:9)
313 error code ETARGET
314 error notarget No matching version found for @typescript-eslint/eslint-plugin@8.
315 error notarget In most cases you or one of your dependencies are requesting
315 error notarget a package version that doesn't exist.
```

**Comment by adarsh4d** [comment]
This is because the v8 of `@typescript-eslint/eslint-plugin` is not released yet. Add the following to `package.json` as a workaround until the stable version is released or its peer dependency is fixed. 
 
```javascript
"overrides": {
    "@typescript-eslint/eslint-plugin": "^8.0.0-alpha.39"
  }
```

**Comment by mcfarljw** [comment]
Might not be related but after setting the `"@typescript-eslint/eslint-plugin": "^8.0.0-alpha.39"` override it does install correctly without any conflicts but running the `eslint .` command getting this:

```
Parsing error: Could not read default project 'tsconfig.json': error TS5083: Cannot read file 'tsconfig.json'
```

**Comment by RayGuo-ergou** [comment]
Hi @mcfarljw that's a breaking change in eslint typescript v8, see https://typescript-eslint.io/blog/announcing-typescript-eslint-v8-beta/#project-service

**Comment by antfu** [comment]
Pending for upstream: https://github.com/sweepline/eslint-plugin-unused-imports/issues/85
