### ISSUE TITLE
Parsing error: Could not read default project 'tsconfig.json': error TS5083: Cannot read file 'tsconfig.json' when tsconfigPath: 'tsconfig.json' set

### ISSUE THREAD

**Issue by vaiil** [antfu/eslint-config#540]
### Describe the bug

I try to setup strict typescript rules adding tsconfig path in options:
```
typescript: {
  tsconfigPath: 'tsconfig.json',
  }
```

I got the following error during linting any ts file:
```
Parsing error: Could not read default project 'tsconfig.json': error TS5083: Cannot read file 'tsconfig.json'
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rxof8k?file=eslint.config.js

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 48.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.asdf/installs/nodejs/20.11.0/bin/node
    Yarn: 1.22.22 - ~/.asdf/installs/nodejs/20.11.0/bin/yarn
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 9.5.0 - ~/.asdf/installs/nodejs/20.11.0/bin/pnpm
  Browsers:
    Chrome Canary: 128.0.6595.0
    Safari: 17.4.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by exherb** [comment]
same here
