### ISSUE TITLE
`eslint-config-flat-gitignore` not enabled in sub-directories of monorepos

### ISSUE THREAD

**Issue by lachlancollins** [antfu/eslint-config#544]
### Describe the bug

I noticed that `eslint-config-flat-gitignore` is only added if the current directory contains a `.gitignore` file:

https://github.com/antfu/eslint-config/blob/6972860890436322e0c150d34b21157de43e7b98/src/factory.ts#L117-L118

However, the package itself supports looking up the directory tree to find a `.gitignore` file.

In my use-case, I'm trying to run eslint in a sub-directory of a monorepo, where there is only a root-level `.gitignore` file. It would be helpful if these ignore rules were utilised by default when running eslint in sub-directories.

### Reproduction

https://codesandbox.io/p/devbox/antfu-repro-8rdlh6

1. Run pnpm lint (will get an error in `/project/workspace/packages/demo/src/index.js`)
2. Rename `/packages/demo/src` to `/packages/demo/ignore` (ignored by root `.gitignore`)
3. Run pnpm lint (will get an error in `/project/workspace/packages/demo/ignore/index.js`)

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 12.85 GB / 15.58 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.11.0 - ~/.volta/tools/image/node/20.11.0/bin/node
    npm: 10.2.5 - ~/.volta/tools/image/npm/10.2.5/bin/npm
    pnpm: 9.4.0 - ~/.volta/bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
This is how it was designed. I am not sure if it's efficient to support nested .gitignores. In that case I would suggest you to manually specify the ignores in your eslint.config.js. Otherwise, you can send a PR to https://github.com/antfu/eslint-config-flat-gitignore to propose your solutions. Thanks.

**Comment by lachlancollins** [comment]
> I am not sure if it's efficient to support nested .gitignores

Hi @antfu, I just wanted to clarify my suggestion, because what I'm requesting is already supported by `eslint-config-flat-gitignore`. I don't expect this to handle multiple nested gitignore files, but just to look for the closest gitignore.

Scenario:

1. In a monorepo, I have a `.gitignore` in the root directory only 
2. If I run `cd packages/package-a && eslint .`, there will not be a gitignore at the current sub-directory, so no ignores will be loaded
3. If the `fs.existsSync` check was removed, then `eslint-config-flat-gitignore` would look up the directory tree and load only the first gitignore it found (i.e. from `../../.gitignore`)

**Comment by antfu** [comment]
I see. PR welcome then. `eslint-config-flat-gitignore` now supports `strict: false` where we no longer need to specify the path of the ignore file explicitly.
