### ISSUE TITLE
Use `fixable: true` for `eslint.rules.customizations`

### ISSUE THREAD

**Issue by Dimava** [antfu/eslint-config#551]
### Describe the bug

There *are* cases where `style/*` rules are not fixable, making them invisible in editor but appearing in lint

Consider modifying readme/wizard `eslint.rules.customizations` to target only `fixable` rules

```diff json
   "eslint.rules.customizations": [
-    { "rule": "style/*", "severity": "off" },
+    { "rule": "style/*", "severity": "off", "fixable": true },
     // ...
```

### Reproduction

```ts
function _foo(_a: {
  a: 1, b: 2
  //  ^! Unexpected separator (,).eslintstyle/member-delimiter-style
}) { }
```

### System Info

```Shell
VSCode@1.91.1
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
OK, want to send a quick PR?
