### ISSUE TITLE
ESLint version conflict caused by eslint-plugin-unused-imports

### ISSUE THREAD

**Issue by yunsii** [antfu/eslint-config#558]
### Describe the bug

![image](https://github.com/user-attachments/assets/d0c3800e-0adb-47b6-9696-e22530f189a7)

It seems to migrate peer dep eslint to v9? As a reacter, I found that eslint-plugin-react-hooks need [extra fix up](https://github.com/facebook/react/issues/28313) for now.

### Reproduction

https://github.com/antfu/eslint-config/blob/d5851d229ff047ad2af49bd725f5cb05c53c2af7/package.json#L46

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 13.44 GB / 15.52 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 9.5.0 - ~/.nvm/versions/node/v18.19.0/bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [x] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by Dimava** [comment]
Considering 
https://github.com/antfu/eslint-config/blob/d5851d229ff047ad2af49bd725f5cb05c53c2af7/package.json#L150
it seems to be forgotten to change

**Comment by yunsii** [comment]
> it seems to be forgotten to change

I don't think so, `eslint` is just a peer dependency, `eslint-ts-patch` is not required for ESLint users.

**Comment by antfu** [comment]
You will need to explicitly install `eslint@v9` along this config. In the next major we will consider to drop ESLint v8 and support v9 only

**Comment by MBurchard** [comment]
I am sorry if I have overlooked something obvious.

If I stay on ESLint 8.57.0, then I get these issues.
```
pnpm i
 WARN  5 deprecated subdependencies found: @humanwhocodes/config-array@0.11.14, @humanwhocodes/object-schema@2.0.3, glob@7.2.3, inflight@1.0.6, rimraf@3.0.2
Packages: +43 -42
+++++++++++++++++++++++++++++++++++++++++++------------------------------------------
Progress: resolved 610, reused 573, downloaded 0, added 0, done

devDependencies:
- eslint 9.7.0
+ eslint 8.57.0 (9.7.0 is available)

 WARN  Issues with peer dependencies found
.
└─┬ @antfu/eslint-config 2.23.2
  └─┬ eslint-plugin-unused-imports 4.0.1
    └── ✕ unmet peer eslint@^9.0.0: found 8.57.0
```

If I switch to ESLint 9.7.0 I get this issues.
```
pnpm i
 WARN  2 deprecated subdependencies found: glob@7.2.3, inflight@1.0.6
Packages: +42 -43
++++++++++++++++++++++++++++++++++++++++++-------------------------------------------
Progress: resolved 609, reused 572, downloaded 0, added 0, done

devDependencies:
- eslint 8.57.0
+ eslint 9.7.0

 WARN  Issues with peer dependencies found
.
└─┬ @antfu/eslint-config 2.23.2
  └─┬ eslint-plugin-perfectionist 2.11.0
    └─┬ @typescript-eslint/utils 7.16.1
      └── ✕ unmet peer eslint@^8.56.0: found 9.7.0
```

Which death should I die ;)?

**Comment by antfu** [comment]
I wonder what would be the reason to stay at `8.57.0`?

**Comment by LouizFC** [comment]
> I wonder what would be the reason to stay at `8.57.0`?

the estlint react-hooks plugin has some issues with v9, see https://github.com/t3-oss/create-t3-turbo/issues/984 for both the issue and the workaround

**Comment by thien-do** [comment]
The best compromise I found is to switch to the beta version of the react hooks plugin. We will instead have a peer warning from antfu eslint, but the react hooks plugin will not crash.

<img width="1264" alt="image" src="https://github.com/user-attachments/assets/979cbfc1-56d1-4d2a-9473-a4ddb0cd5591">

**Comment by Rel1cx** [comment]
In the latest [version 1.8.0](https://github.com/Rel1cx/eslint-react/releases/tag/v1.8.0), `@eslint-plugin/eslint-react` now officially supports `typescript-eslint` v8 and ESLint v9.

**Comment by pavitra-infocusp** [comment]
Here's more:

```
 WARN  Issues with peer dependencies found
.
└─┬ @antfu/eslint-config 2.24.1
  └─┬ eslint-plugin-import-x 3.1.0
    └─┬ @typescript-eslint/utils 7.18.0
      └── ✕ unmet peer eslint@^8.56.0: found 9.8.0
```

**Comment by darthf1** [comment]
Same issue with peer deps on `eslint-plugin-import-x`:

```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @antfu/eslint-config 2.25.1
  └─┬ eslint-plugin-import-x 3.1.0
    └─┬ @typescript-eslint/utils 7.18.0
      └── ✕ unmet peer eslint@^8.56.0: found 9.9.0

hint: If you don't want pnpm to fail on peer dependency issues, add "strict-peer-dependencies=false" to an .npmrc file at the root of your project.
```

**Comment by pauliesnug** [comment]
Yeah this was fixed, for the other plugins just use `strict-peer-dependencies=false` for now.

**Comment by nsteinmetz** [comment]
For the record, I still have this one:

```
└─┬ @antfu/eslint-config 2.26.0
  └─┬ eslint-plugin-import-x 3.1.0
    └─┬ @typescript-eslint/utils 7.18.0
      └── ✕ unmet peer eslint@^8.56.0: found 9.9.0
```

But it should be fixed soon according to https://github.com/un-ts/eslint-plugin-import-x/issues/121#issuecomment-2290010001

**Comment by antfu** [comment]
I am closing this for now. For `eslint-plugin-import-x` I will upgrade to it as soon as they release the new version
