### ISSUE TITLE
`unused-imports/no-unused-imports` is not run on pre-commit hook in VSCode

### ISSUE THREAD

**Issue by MKraust** [antfu/eslint-config#560]
### Describe the bug

I use VSCode default UI for commits. When I'm doing commit, VSCode runs git command under the hood and sets `VSCODE_PID` env var, which is recognized by `isInEditorEnv` function.

To be sure that it is because of VSCode, I've added `env | grep VSCODE` command to pre-commit hook.

Output when commited from terminal with `git commit -am "foo"`:
```
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_INJECTION=1
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
VSCODE_GIT_IPC_HANDLE=/var/folders/lp/vth90wsd5txdp0_fs0f2kvjc0000gn/T/vscode-git-6240df4a0e.sock
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
```

Output when commited from VSCode UI:
```
VSCODE_CRASH_REPORTER_PROCESS_TYPE=extensionHost
VSCODE_AMD_ENTRYPOINT=vs/workbench/api/node/extensionHostProcess
VSCODE_HANDLES_UNCAUGHT_ERRORS=true
VSCODE_GIT_COMMAND=-c
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
VSCODE_NLS_CONFIG={"locale":"ru","osLocale":"ru-kz","availableLanguages":{"*":"ru"},"_languagePackId":"6161035fc9c584bdacea90e27f514acf.ru","_translationsConfigFile":"/Users/kraust/Library/Application Support/Code/clp/6161035fc9c584bdacea90e27f514acf.ru/tcf.json","_cacheRoot":"/Users/kraust/Library/Application Support/Code/clp/6161035fc9c584bdacea90e27f514acf.ru","_resolvedLanguagePackCoreLocation":"/Users/kraust/Library/Application Support/Code/clp/6161035fc9c584bdacea90e27f514acf.ru/f1e16e1e6214d7c44d078b1f0607b2388f29d729","_corruptedFile":"/Users/kraust/Library/Application Support/Code/clp/6161035fc9c584bdacea90e27f514acf.ru/corrupted.info","_languagePackSupport":true}
VSCODE_CODE_CACHE_PATH=/Users/kraust/Library/Application Support/Code/CachedData/f1e16e1e6214d7c44d078b1f0607b2388f29d729
VSCODE_GIT_IPC_HANDLE=/var/folders/lp/vth90wsd5txdp0_fs0f2kvjc0000gn/T/vscode-git-6240df4a0e.sock
VSCODE_IPC_HOOK=/Users/kraust/Library/Application Support/Code/1.91-main.sock
VSCODE_PID=56456
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
VSCODE_CWD=/
VSCODE_L10N_BUNDLE_LOCATION=file:///Users/kraust/.vscode/extensions/ms-ceintl.vscode-language-pack-ru-1.91.2024071009/translations/extensions/vscode.json-language-features.i18n.json
```

P.S. Actually, I like behavior when this rule is not run while actually editing the code and I don't want to set `isInEditor: false`. I think we can use other flags in `isInEditorEnv` function, e.g. `(process.env.VSCODE_PID && !process.env.VSCODE_GIT_COMMAND) || ...`.

### Reproduction

Is it needed for such case?

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 110.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
    bun: 1.0.4 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by pauliesnug** [comment]
This was fixed in the latest version
