### ISSUE TITLE
Breaks when the `tsconfig.json` file has `extends`

### ISSUE THREAD

**Issue by kevbook** [antfu/eslint-config#564]
### Describe the bug

I keep getting the following error when I use a `tsconfig.json` with `extends`

```
  0:0  error  Parsing error: Cannot read properties of undefined (reading 'target')
```

```ts
export default antfu({
  typescript: { 
    tsconfigPath: resolve(process.cwd(), 'tsconfig.json')
   }
});
```

// Project tsconfig.json

```json
{
  "extends": "./base-tsconfig.json"
}
```

`base-tsconfig.json` file contains the company-wide standard config. This is typically another npm package, but for now just a local file.

Let me know if I need to provide any more details. I just started getting this error since the last update.

### Reproduction

```shell
$ eslint . 
```

### System Info

```shell
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M3
  Memory: 70.64 MB / 16.00 GB
  Shell: 3.2.57 - /bin/bash

Binaries:
  Node: 20.15.1 - /usr/local/bin/node
  npm: 10.7.0 - /usr/local/bin/npm
  pnpm: 9.6.0 - ~/Library/pnpm/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by kevbook** [comment]
I just confirmed, the last working version is `v2.21.3`

**Comment by pauliesnug** [comment]
This is probably an upstream issue with typescript-eslint@8

**Comment by antfu** [comment]
Yeah this might be an upstream issue. Please report to typescript-eslint with a minimal reproduction for them.

**Comment by kevbook** [comment]
Seems to be fixed now
