### ISSUE TITLE
Parsing error with Nuxt and TypeScript

### ISSUE THREAD

**Issue by iamwxq** [antfu/eslint-config#565]
### Describe the bug

Hi, thanx for your awesome repo.

I found a parsing error when I use your eslint-config with Nuxt and TypeScript. I generated it by the .
You can check it with my minimal repo. It shows that eslint seems can't properly parse .vue file with `<script setup lang="ts"></script>`

screenshot:

![eslint](https://github.com/user-attachments/assets/f090075e-94d4-44d2-8ce0-7486b803a3cc)

### Reproduction

https://stackblitz.com/edit/nuxt-starter-6fuuku

### System Info

```Shell
System:
    设备名称	DESKTOP-1R0P5I0
    处理器	13th Gen Intel(R) Core(TM) i7-13700K   3.40 GHz
    机带 RAM	64.0 GB (63.7 GB 可用)
    系统类型	64 位操作系统, 基于 x64 的处理器
  Binaries:
    Node: 20.15.1
    npm: 10.7.0
    pnpm: 9.6.0
  Browsers:
    Chrome: 126.0.6478.183
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
Try to install `typescript` in your project root

**Comment by iamwxq** [comment]
thanks a lot! it could be solved after installing typescript
