### ISSUE TITLE
i cant ignore root folder

### ISSUE THREAD

**Issue by yyqxjwxy** [antfu/eslint-config#568]
### Describe the bug

I want to ignore a folder in src in my root directory but the configuration doesn't work
```javascript
// eslint.config.js
import antfu from '@antfu/eslint-config'

export default antfu({
  ignores: [
    'src/router/elegant',
    'src/views/enterprise-chart',
    'src/views/personal-chart',
  ],
  formatters: {
  /**
   * Format CSS, LESS, SCSS files, also the `<style>` blocks in Vue
   * By default uses Prettier
   */
    css: true,
    /**
     * Format HTML files
     * By default uses Prettier
     */
    html: true,
    /**
     * Format Markdown files
     * Supports Prettier and dprint
     * By default uses Prettier
     */
    markdown: 'prettier',
  },
  rules: {
    'vue/component-name-in-template-casing': ['error', 'kebab-case'],
    'eslint-comments/no-unlimited-disable': 'off',
  },

})
``` 

### Reproduction

Reproduction

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 57.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - ~/.nvm/versions/node/v22.2.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v22.2.0/bin/npm
    pnpm: 9.1.2 - ~/Library/pnpm/pnpm
    bun: 1.0.26 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.185
    Safari: 17.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
You need to do `src/router/elegant/**`
