### ISSUE TITLE
Upgrade from `2.23.0` to `2.24.0` introduced a breaking dependency update, forcing node v20 as the new baseline

### ISSUE THREAD

**Issue by chrisspiegl** [antfu/eslint-config#569]
### Describe the bug

I just upgraded the package to `v2.24.0`
My project is still using v18 since it's the LTS we are building on.
`v2.24.0` could not be installed because dependency minimatch in `eslint-plugin-perfectionist` is now requiring node v20 or 22.

This feels like a breaking change even for this library, to drop support for the LTS 18 version?

I just think a mention in the release notes, README, or maybe a major version update would be some good ways to handle this, no?

```console
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

This error happened while installing the dependencies of @antfu/eslint-config@2.24.0
 at eslint-plugin-perfectionist@3.0.0

Your Node version is incompatible with "minimatch@10.0.1".

Expected version: 20 || >=22
Got: v18.20.4
```

### Reproduction

install package at v2.24.0 with node v18 and see the install break

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.36 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.4 - ~/Library/pnpm/node
    npm: 10.7.0 - ~/Library/pnpm/npm
    pnpm: 9.6.0 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 126.1.67.134
    Safari: 17.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
I am ok to revert that change, PR welcome :)

**Comment by antfu** [comment]
https://github.com/antfu/eslint-config/pull/632#issuecomment-2484488546
