### ISSUE TITLE
Unable to use `react` config on ESLint v9

### ISSUE THREAD

**Issue by fregante** [antfu/eslint-config#571]
This is not strictly a bug with the config, but it's because the stable version of eslint-plugin-react-hooks (v4) does not have ESLint 9 as a peer config.

As suggested by @thien-do in https://github.com/antfu/eslint-config/issues/558#issuecomment-2253039214, you can install the beta version.

### Steps to fix it temporarily

1. Add `legacy-peer-deps=true` to your .npmrc file
2. Add a `react` key to your `antfu()` config
5. Run `npm install -D eslint-plugin-react-hooks@beta`
3. Run eslint 

### Related issues to follow

- https://github.com/facebook/react/issues/28313

**Comment by rvanbaalen** [comment]
Can confirm this is still an issue. Use the config CLI or manual config with `react: true` and you can't install the dependencies due to incompatibility between peer deps.

Using the above steps resolved the issue (allowing legacy peer deps and installing `eslint-plugin-react-hooks@beta`)
