### ISSUE TITLE
Switch from eslint-plugin-vitest to eslint-plugin-vitest-latest

### ISSUE THREAD

**Issue by HummingMind** [antfu/eslint-config#576]
### Describe the bug

Switch from eslint-plugin-vitest to eslint-plugin-vitest-latest. The author of eslint-plugin-vitest was having issues with NPM. He had to rename the package to eslint-plugin-vitest-latest to be able to publish the newer versions. Newer versions fix the outadeted dependency on an older version of @typescript-eslint/utils.

Looks like they also created @vitest/eslint-plugin, so maybe used that one instead.

Thank you.

### Reproduction

N/A

### System Info

```Shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by pauliesnug** [comment]
Yes, `@vitest/eslint-plugin` is the new official one.
