### ISSUE TITLE
`ignoresTypeAware` breaks typescript parsing in those files

### ISSUE THREAD

**Issue by kunokareal** [antfu/eslint-config#578]
### Describe the bug

passing a file into `ignoresTypeAware` breaks parsing in those files (see repro)

```bash
❱ pnpm eslint

/Users/kunoka/repo/antfu-repro/src/not-type-aware.ts
  1:8  error  Parsing error: Unexpected token :

/Users/kunoka/repo/antfu-repro/src/type-aware.ts
  3:7   error  Unsafe assignment of an `any` value                ts/no-unsafe-assignment
  3:18  error  Unsafe member access .someField on an `any` value  ts/no-unsafe-member-access

✖ 3 problems (3 errors, 0 warnings)
```

passing the `type-aware.ts` explicitly in `filesTypeAware`, removing the `ignoresTypeAware` or disabling type-aware linting fixes the issue.

### Reproduction

https://github.com/kunokareal/antfu-repro

### System Info

```Shell
System:
    OS: macOS 15.0
    CPU: (14) arm64 Apple M3 Max
    Memory: 74.72 MB / 24.00 GB
    Shell: 5.9 - /etc/profiles/per-user/kunoka/bin/zsh
  Binaries:
    Node: 20.15.1 - ~/Library/Caches/fnm_multishells/92006_1723512194100/bin/node
    npm: 10.7.0 - ~/Library/Caches/fnm_multishells/92006_1723512194100/bin/npm
    pnpm: 9.5.0 - ~/Library/Caches/fnm_multishells/92006_1723512194100/bin/pnpm
    bun: 1.1.20 - ~/.bun/bin/bun
  Browsers:
    Chrome: 127.0.6533.100
    Safari: 18.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by kunokareal** [comment]
i initially had a similar issue to #570, which only seems to occur when i pass `ignoresTypeAware` option, and the solution in the comments doesn't really work, so that's also something

but while trying to make a minimal repro i ended up with this :>

**Comment by pauliesnug** [comment]
I think this is intentional, or at least is what the code is intended to do. `ignoresTypeAware` is passed into `antfu/typescript/parser` configuration as regular `ignores`
