### ISSUE TITLE
`Note: detected a parser other than @typescript-eslint/parser` (Because of vue)

### ISSUE THREAD

**Issue by phoenix-oes** [antfu/eslint-config#586]
### Describe the bug

I'm getting a _very similar_ error as #570 (but due to a different cause) when I use this config (and no other rules configured):

```mjs
import antfu from '@antfu/eslint-config'
import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat()

export default antfu(
  {
    ignores: [
      'node_modules',
      '.pnpm-store',
    ],
  },
  ...compat.extends(
    // 'plugin:vue/vue3-essential',
    'plugin:vue/vue3-recommended',
    // '@vue/eslint-config-typescript/recommended',
    // (It doesn't work for any of these)
  ),
)
```

While this _appears_ to be consistent with the Legacy Config instructions in the readme, I get the following error:

```txt
> eslint .


Oops! Something went wrong! :(

ESLint: 8.57.0

Error: Error while loading rule 'ts/consistent-type-imports': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Parser: vue-eslint-parser
Note: detected a parser other than @typescript-eslint/parser. Make sure the parser is configured to forward "parserOptions.project" to @typescript-eslint/parser.
Occurred while linting /workspaces/scale/quasar.config.ts
...
```

It's trying to use the `vue-eslint-parser` on a non-vue `.ts` file. I thought Vue stuff was handled automatically?

I imagined it would be solvable by doing something like:

```mjs
import antfu from '@antfu/eslint-config'
import { FlatCompat } from '@eslint/eslintrc'
import tsParser from '@typescript-eslint/parser'
import vueParser from 'vue-eslint-parser'

const compat = new FlatCompat()

export default antfu(
  {
    ignores: [
      'node_modules',
      '.pnpm-store',
    ],
  },
  ...compat.extends(
    'plugin:vue/vue3-recommended',
  ),
  {
    files: ['*.ts', '*.tsx'],
    languageOptions: {
      parser: tsParser,
    },
  },
  {
    files: ['*.vue'],
    languageOptions: {
      parser: vueParser,
    },
  },
)
```

But it _still fails_.

```txt
> eslint .


Oops! Something went wrong! :(

ESLint: 8.57.0

Error: Error while loading rule 'ts/consistent-type-imports': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Parser: vue-eslint-parser
Note: detected a parser other than @typescript-eslint/parser. Make sure the parser is configured to forward "parserOptions.project" to @typescript-eslint/parser.
Occurred while linting /workspaces/scale/src/quasar.d.ts
...
```

This time in a different file (`quasar.d.ts` instead of `quasar.config.ts`).

Taking out the `files` line from the Typescript section **does** allow the linter to "run"... except now it's trying to use the Typescript parser for everything. So, the `package.json`, for example, is one big "error". Since JSON is not valid Typescript.

### Reproduction

The configuration file above

### System Info

```Shell
System:
    OS: Linux 6.5 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 69.35 GB / 125.73 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 22.5.1 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 9.7.1 - /usr/local/share/npm-global/bin/pnpm

Using:

    "@antfu/eslint-config": "^2.26.0",
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
Why would you need to configure Vue by your own? I believe it's more like your own configuration issue, as our Vue integrations works fine.

**Comment by Dimava** [comment]
@phoenix-oes you don't need this, vue:recommended is already included if you enable Vue
https://github.com/antfu/eslint-config/blob/172f9037cfa6ffae47b1bb5a215091470b09e674/src/configs/vue.ts#L102
