### ISSUE TITLE
"node:test" gets rewritten as "vitest"

### ISSUE THREAD

**Issue by danielrhodes** [antfu/eslint-config#602]
### Describe the bug

Whenever the linter is run, if I have written something like:

```
import { describe } from 'node:test'
```

it rewrites it as

```
import { describe } from 'vitest'
```

There is no configuration on eslint.config.js ... It is the following:

```
import antfu from '@antfu/eslint-config'

export default antfu({

})
```

### Reproduction

Create a file called some.test.ts and run the following above

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 330.11 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 8.15.5 - ~/Library/pnpm/pnpm
    bun: 1.0.33 - ~/.bun/bin/bun
    Watchman: 2024.08.19.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 128.0.6613.114
    Chrome Canary: 130.0.6695.1
    Firefox Nightly: 129.0a1
    Safari: 17.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
That's intended. You can disable the rule. https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/no-import-node-test.md

**Comment by antfu** [comment]
Because this is my config, just a reminder.
