### ISSUE TITLE
Rule "antfu/consistent-chaining" isn't really consistent

### ISSUE THREAD

**Issue by ThibaultVlacich** [antfu/eslint-config#603]
### Describe the bug

You can see directly the issue on the commit that the rule was introduced:

```
  let num = Math
  .floor (Math.random() * 1E+7).toString()
    .replace(/\.\d+/ig, "")
```
`.toString` is not on a new line, and `.floor` is not aligned with `.replace`

```
  const num = Math
    .floor (Math.random() * 1e+7)
    .toString()
    .replace(/\.\d+/g, '')
```
Here everything is fine

### Reproduction

https://github.com/antfu/eslint-config/commit/d6dfc4e5a429e7ed3d0d00f79234a2cea52ed5af

### System Info

```Shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
What do you mean? You are looking that the **input**, where the output looks fine to me

**Comment by ThibaultVlacich** [comment]
> What do you mean? You are looking that the **input**, where the output looks fine to me

Oh right, my bad. I'll try to make an actual reproduction then, based on some inconsistencies I noticed in my own project after updating to the latest version :)
