### ISSUE TITLE
The js rule options were ignored when mapping to ts

### ISSUE THREAD

**Issue by lvjiaxuan** [antfu/eslint-config#609]
### Describe the bug

js rule with options:
![image](https://github.com/user-attachments/assets/23dc10cd-7fa0-463d-bd6a-7c8ab2bb0cf6)

ts rule without options:
![image](https://github.com/user-attachments/assets/5ab2f2a5-babc-47be-b5ef-7e7b52c56cc0)

I have found 2 such rules, if im not mistaken:
![image](https://github.com/user-attachments/assets/c09de1da-f2c6-4633-aebc-09be7b129f9f)

### Reproduction

This repo itself.

### System Info

```Shell
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 8.12 GB / 15.81 GB
  Binaries:
    Node: 20.15.1 - d:\nvm\nodejs\node.EXE
    Yarn: 1.22.19 - d:\nvm\nodejs\yarn.CMD
    npm: 10.7.0 - d:\nvm\nodejs\npm.CMD
    pnpm: 9.10.0 - d:\nvm\nodejs\pnpm.CMD
    bun: 1.1.7 - ~\.bun\bin\bun.EXE
  Browsers:
    Chrome: 128.0.6613.138
    Internet Explorer: 11.0.17763.2989
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
Oh I see. PR welcome! Thank you
