### ISSUE TITLE
Merge prettier plugins for formatters

### ISSUE THREAD

**Issue by suppayami** [antfu/eslint-config#613]
### Clear and concise description of the problem

Currently for each supported formatters, the rules overrides `plugins` field from `options.prettierOptions`. This makes it hard to use any other prettier plugins, such as `prettier-plugin-tailwindcss`.

### Suggested solution

Merge `plugins` from `prettierOptions` with final prettier rules, for example:

```javascript
antfu({
  formatters: {
    astro: true,
    prettierOptions: {
      plugins: ['prettier-plugin-tailwindcss'],
    },
  },
})
```

### Alternative

Alternative would be this PR, but supporting suggested solution would be easier for most users https://github.com/antfu/eslint-config/pull/592

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sounds good, PR welcome :)
