### ISSUE TITLE
`antfu/no-top-level-await` is not ignored in Markdown files

### ISSUE THREAD

**Issue by rileychh** [antfu/eslint-config#616]
### Describe the bug

After updating to 3.7.0, the new `antfu/no-top-level-await` rule reports problems in code blocks with `await` in Markdown files, e.g.:

    ```typescript
    import { formMetadataSelect } from './index.get'
    
    return await prisma.form.create({
      select: formMetadataSelect,
      data: { /* ... */ },
    })
    ```

The above violates `antfu/no-top-level-await` while it should not be applied to documentation.

### Reproduction

https://stackblitz.com/edit/top-level-await-repro?file=README.md&view=editor

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by pauliesnug** [comment]
fixed in latest version

**Comment by curtgrimes** [comment]
Link to the commit that fixes this, if helpful: https://github.com/antfu/eslint-config/commit/a984c89ba435b1db471d317f2139de851456f8b8
