### ISSUE TITLE
Unable to run pnpm dlx @ antfu/ eslint-config@latest

### ISSUE THREAD

**Issue by RanMaoting** [antfu/eslint-config#617]
### Describe the bug

When I run pnpm dlx @ antfu/ eslint-config@latest The following output information is available on the console
![image](https://github.com/user-attachments/assets/eb60e5ba-8877-41cd-aea4-32546b384179)
May I ask how I can solve it? Thank you

### Reproduction

-

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
    Memory: 3.51 GB / 31.30 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.11.0 - ~\AppData\Local\Microsoft\WinGet\Packages\pnpm.pnpm_Microsoft.Winget.Source_8wekyb3d8bbwe\pnpm.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by i7slegend** [comment]
npx same on the 3.7.3
```
While resolving: undefined@undefined
Found: @antfu/eslint-config@2.24.0
node_modules/@antfu/eslint-config
  @antfu/eslint-config@"3.7.3" from the root project

Could not resolve dependency:
@antfu/eslint-config@"3.7.3" from the root project

Conflicting peer dependency: eslint@9.11.1
node_modules/eslint
  peer eslint@"^9.10.0" from @antfu/eslint-config@3.7.3
  node_modules/@antfu/eslint-config
    @antfu/eslint-config@"3.7.3" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

On previous version (3.7.2) no errors

System is Ubuntu via WSL:
```
  System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
    Memory: 21.15 GB / 31.04 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
```

**Comment by i7slegend** [comment]
> npx same on the 3.7.3
> 
> ```
> While resolving: undefined@undefined
> Found: @antfu/eslint-config@2.24.0
> node_modules/@antfu/eslint-config
>   @antfu/eslint-config@"3.7.3" from the root project
> 
> Could not resolve dependency:
> @antfu/eslint-config@"3.7.3" from the root project
> 
> Conflicting peer dependency: eslint@9.11.1
> node_modules/eslint
>   peer eslint@"^9.10.0" from @antfu/eslint-config@3.7.3
>   node_modules/@antfu/eslint-config
>     @antfu/eslint-config@"3.7.3" from the root project
> 
> Fix the upstream dependency conflict, or retry
> this command with --force or --legacy-peer-deps
> to accept an incorrect (and potentially broken) dependency resolution.
> ```
> 
> On previous version (3.7.2) no errors
> 
> System is Ubuntu via WSL:
> 
> ```
>   System:
>     OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
>     CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
>     Memory: 21.66 GB / 31.04 GB
>     Container: Yes
>     Shell: 3.3.1 - /usr/bin/fish
>   Binaries:
>     Node: 18.19.1 - ~/.local/share/nvm/v18.19.1/bin/node
>     Yarn: 1.22.22 - ~/.nvm/versions/node/v14.15.5/bin/yarn
>     npm: 10.2.4 - ~/.local/share/nvm/v18.19.1/bin/npm
>     pnpm: 9.5.0 - ~/.nvm/versions/node/v14.15.5/bin/pnpm
> ```

Now ok. Can't reproduce it

**Comment by alniv94** [comment]
got the same issue

![Image](https://github.com/user-attachments/assets/2082a98d-256b-470e-94e7-95b06c401c25)
