### ISSUE TITLE
[Question] Loading additional plugin doesn't seem to do anyting

### ISSUE THREAD

**Issue by oluijks** [antfu/eslint-config#621]
### Describe the bug

Perhaps I'm doing things wrong but I want to include `@tanstack/eslint-plugin-query` in my config.

In my old config I had something like:

```
extends: [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginQuery.configs['flat/recommended'],
],
plugins: {
  'react-hooks': reactHooks,
  'react-refresh': reactRefresh,
  '@tanstack/query': pluginQuery,
},
```

I figured I would update the new config like this:

```
export default antfu({
  formatters: true,
  react: true,
  stylistic: {
    indent: 2,
    semi: true,
    quotes: 'single',
  },
  plugins: {
    '@tanstack/query': pluginQuery,
    '@tanstack/router': pluginRouter,
  },
});
```

### Reproduction

none

### System Info

```Shell
System:
    OS: Linux 6.11 Arch Linux
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-1360P
    Memory: 6.19 GB / 15.22 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 9.12.1 - ~/.local/share/pnpm/pnpm
    bun: 1.1.29 - ~/.bun/bin/bun
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by eneeio-nm** [comment]
For what it's worth my config using `@tanstack/eslint-plugin-query` looks like this:

```js
// eslint.config.mjs
import antfu from '@antfu/eslint-config'
import pluginQuery from '@tanstack/eslint-plugin-query'

export default antfu({
  ignores: [
    '**/packages/**/',
    'packages/',
  ],
  toml: false,
  yaml: false,
  ...pluginQuery.configs['flat/recommended'],
}, {
  files: ['**/*.vue'],
  rules: {
    'vue/max-attributes-per-line': ['error', {
      singleline: {
        max: 1,
      },
      multiline: {
        max: 1,
      },
    }],
  },
})
```

**Comment by oluijks** [comment]
@eneeio-nm Thanks I will try that and yeah sorry I should have asked this in discussions ;-(
