### ISSUE TITLE
Add Oxlint implementation guide and CLI option

### ISSUE THREAD

**Issue by runyasak** [antfu/eslint-config#631]
### Clear and concise description of the problem

I noticed the Oxlint implementation in `@antfu/eslint-config` mentioned in #535.
It would be great to include an Oxlint implementation guide in the README and provide an option for Oxlint in the starter wizard CLI during installation.

### Suggested solution

* Add a description and details for Oxlint implementation in the README.
* Add an option for Oxlint implementation to the starter wizard CLI.

### Additional context

If you have any feedback or suggestions, please let me know.
I’d be happy to create a pull request to contribute this feature.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I don't think we are ready to have "official docuemented guide" for oxlint yet, maybe until one day after I would give it a deeper look and know the trade-offs. Before that, I don't want to maintain this extra complexities here and receive issues I couldn't help.

On the oxlint side, I am still watching and waiting for a proper plugins system.

**Comment by runyasak** [comment]
I understand. Thank you so much. 😊

**Comment by horvbalint** [comment]
@antfu is this still the case  now, that oxlint 1.0.0 is out? If you had the time to look into it and liked it, I think some documentation would be nice :)

**Comment by Dimava** [comment]
@horvbalint oxlint doesn't have a formatter, and this config heavily depends on Stylistic for formatting
And I don't know any modern formatters that are this extensible
Having a oxlint config with biome formatter would be great but that'd be a completely different config

I'm interested in what Anfu thinks about this as well

**Comment by asonnleitner** [comment]
bump
