### ISSUE TITLE
how to make override work?

### ISSUE THREAD

**Issue by cyfung1031** [antfu/eslint-config#65]
i am using vitesse, i want to override some rules in eslintrc but seems not working.

.eslintrc.js
```js
module.exports = {
  extends: [
    '@antfu',
  ],
  rules: {
    'object-shorthand': ['never'],
  },
}
```

![image](https://user-images.githubusercontent.com/44498510/137578733-56b0be6a-9154-493e-a0bc-6c52754aded5.png)

I tried this too but still not working

![acdfvgfgbhg](https://user-images.githubusercontent.com/44498510/137578885-a99a2f55-c985-4a45-8943-193db491dccd.PNG)

**Comment by maninak** [comment]
Try `'object-shorthand': ['error', 'never'],`

Source: https://eslint.org/docs/user-guide/getting-started#configuration
