### ISSUE TITLE
Eslint 8 version

### ISSUE THREAD

**Issue by riderx** [antfu/eslint-config#68]
Do you plan to migrate to Eslint 8 ?
Can we help on that ?

**Comment by antfu** [comment]
We are on eslint 8, what do you mean?

**Comment by riderx** [comment]
@antfu submodule do not use eslint 8 `eslint-plugin-promise` and `eslint-config-standard` 
<img width="582" alt="Captura de ecrã 2021-12-27, às 19 47 25" src="https://user-images.githubusercontent.com/4084527/147499223-f3a59357-78d9-4000-9de6-63deb8a00881.png">

i discovered this one still doesn't support eslint 8 https://github.com/standard/eslint-config-standard/issues/192
but the other one do : https://github.com/xjamundx/eslint-plugin-promise
if you update to v6.0.0

**Comment by antfu** [comment]
Thanks for bringing this up. I have upgraded them with the current latest. (actually, I found them works on eslint 8 even they say they don't)
