### ISSUE TITLE
question: introducing Prettier?

### ISSUE THREAD

**Issue by jondot** [antfu/eslint-config#69]
I found that for having consistent commits (extra newline, if/else new curlies, etc.) adding prettier on top avoids having two different programmers have an inconsistent style. So far there are virtually no conflicts, my configuration is as follows:

![image](https://user-images.githubusercontent.com/83390/152655646-79550a02-ac4e-46db-ba12-27d0030921c9.png)

**Comment by jondot** [comment]
I'm not sure if this adds processing overhead to eslint, but all in all the experience is great.

**Comment by antfu** [comment]
No, I am not a fan of using eslint and prettier together. This config already doing quite some formatting lint and I would prefer to leave the rest of flexibility and styling to human.

**Comment by sxzz** [comment]
If you like, you can try my fork. https://github.com/sxzz/eslint-config

**Comment by KnifeFed** [comment]
If you want to use this config together with Prettier, you can install `eslint-config-prettier` and add `'prettier'` as the last item to `extends`. This will disable all core ESLint rules that are not needed or conflict with Prettier.
