### ISSUE TITLE
Conflict in VSCode between plugin:vue/vue3-recommended and @antfu/estlint-config-vue

### ISSUE THREAD

**Issue by xokflocc** [antfu/eslint-config#70]
I was trying to use Vitesse and my vscode shows a strange error like the image below:

![image](https://user-images.githubusercontent.com/92298929/155866427-5e11e76f-cefb-4668-9418-3ae701a421c6.png)

I've opened the output, and shows this message:

![image](https://user-images.githubusercontent.com/92298929/155866445-d2c2fd2c-a132-482b-82fb-8f8a2d67f82a.png)

This message appears in every typing I made. I was looking to fix it, and I'm discover that if I comment the line 17 of the @antfu/eslint-config-vue/index.js, the errors disapear in my screen, like the image below:

![image](https://user-images.githubusercontent.com/92298929/155866484-5d2e7722-666e-4a93-a8b1-b904e801aaf7.png)

I think this could be a problem in eslint itself, but I come here first just to see if you made something magic, like Vitesse (I really like Vitesse).

**Comment by antfu** [comment]
Why not use `@antfu/eslint-config`?

**Comment by xokflocc** [comment]
I'm sorry to not explain well. The problem I found in your package. I made the changes directly in your package.
