### ISSUE TITLE
webStorm  ESLint : Error : Failed to webStorm 编辑器里面提示未能加载插件

### ISSUE THREAD

**Issue by rudy-lc** [antfu/eslint-config#71]
大佬您好这个 eslint-config 的配置在 webStorm 编辑器里面提示未能加载插件
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/23306072/158122849-6b30a3f2-e070-414f-9d09-9fa1a28b0918.png">

**Comment by antfu** [comment]
我自己并不用 WebStorm，VS Code 是没有问题的，你可能要自己 debug 了
