### ISSUE TITLE
why disable no-undef / no-unused-vars?

### ISSUE THREAD

**Issue by mariusa** [antfu/eslint-config#72]
Hi,

I find `no-undef / no-unused-vars` very useful.
Since installing `antfu/eslint-config`, I noticed the warnings were lost.
Found this: https://github.com/antfu/eslint-config/commit/46a8d7acdee3a99d6838bf427c6fd2b133f70ddc

What's the reasoning, please?

Thanks

**Comment by antfu** [comment]
I use TypeScript, which already handles that so I don't need this duplication.

**Comment by mariusa** [comment]
Ok, thanks.

Would you know how to overwrite just these settings? In `.eslintrc` I tried
```js
module.exports = {
...
    extends: ["eslint:recommended", "plugin:vue/base", "plugin:vue/vue3-essential", "plugin:vue/vue3-recommended", "plugin:vue/vue3-strongly-recommended", "@antfu"],
...
   overrides: [ 
    {
	"files": ["*.vue"],
	"rules": {
	    'no-unused-vars': 'warn',
            'no-undef': 'warn',
	    '@typescript-eslint/no-unused-vars': 'warn',
	}
    } 
    ]
```
but the rule is still off.
