### ISSUE TITLE
why put eslint plugin/config into `dependencies`?

### ISSUE THREAD

**Issue by HomyeeKing** [antfu/eslint-config#75]
I am looking through pnpm source code recently and find out the author [put eslint relative thing into `dependencies`](https://github.com/pnpm/pnpm/blob/688b0eaff929513e97673b2da8cd3a2da18f677a/utils/eslint-config/package.json#L26)as an `eslint-config` package. Then I check this repo, same with pnpm eslint-config

it's really confusing me because it against my acknowledge w/ dependencies, it's more reasonable for me to put the lint\build\transpiler tool into `devDependencies`

and I have already tested locallly, it still works when you put them into `devDependencies`, so I can't help [opening a ticket](https://stackoverflow.com/questions/71569915/how-bundler-handle-the-dependencies-and-why-put-eslint-thing-into-dependencies),
as far I know, I [prefer @ljhard's answer](https://github.com/facebook/create-react-app/issues/3209#issuecomment-336602578), so I want to hear from you, what do you think?

**Comment by antfu** [comment]
Because you **want** those deps to be installed when you install the main package. Put eslint related things under devDependencies for **libs and apps**

**Comment by HomyeeKing** [comment]
@antfu  you won't miss those deps even though you put them in devDependencies of the main package

**Comment by antfu** [comment]
Please do the test yourself.
