### ISSUE TITLE
vuecli创建的vue3项目 没有引入ts的话,用@antfu/eslint-config会报错

### ISSUE THREAD

**Issue by shilianmalaxiangguo** [antfu/eslint-config#79]
报错如下
`Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js » @antfu/eslint-config » @antfu/eslint-config-react » @antfu/eslint-config-ts': Cannot find module 'typescript'`

请问不是ts项目也能用您的配置吗

**Comment by antfu** [comment]
用 `@antfu/eslint-config-basic` (但是没有 Vue)
