### ISSUE TITLE
The rule "no-leading-newline" is existed in ESLint

### ISSUE THREAD

**Issue by coderzhaoziwei** [antfu/eslint-config#80]
```
'no-multiple-empty-lines': ['error', { max: 1, maxBOF: 0, maxEOF: 1 }],
```

max - 最大连续空行数
maxBOF - 文件开始的最大连续空行数
maxEOF - 文件末尾的最大连续空行数

==> [no-multiple-empty-lines](https://eslint.org/docs/rules/no-multiple-empty-lines)

**Comment by antfu** [comment]
PR welcome :)
