### ISSUE TITLE
These json rules seems not works

### ISSUE THREAD

**Issue by aliuq** [antfu/eslint-config#85]
If want to change default behaivior, these rules should be add prefix `jsonc`, likes `package.json` rules

```js
'jsonc/comma-dangle': ['error', 'never'],
```

https://github.com/antfu/eslint-config/blob/b8fe1fabea9cdcae1ea78032f172e03994cce1e6/packages/basic/index.js#L43-L51

![image](https://user-images.githubusercontent.com/11707934/165106686-7319f49b-baf8-47f1-a916-1c0330b0623a.png)

![image](https://user-images.githubusercontent.com/11707934/165106762-2a0a92b0-60c3-4d12-9f42-452a2865bdfd.png)

**Comment by aliuq** [comment]
Hopes to add `ignorePatterns: ['!.*.json'],` option for support `.test.json` dotfiles

**Comment by antfu** [comment]
Sorry I can't help with your project. If you find there is any mis configure, feel free to open a PR.

**Comment by aliuq** [comment]
> Sorry I can't help with your project. If you find there is any mis configure, feel free to open a PR.

yeah, I submitted a pr and now the comma dangle at the end of the json file is automatically removed

maybe dotfiles is my personal needs
