### ISSUE TITLE
How to disable react config when extending from `@antfu`

### ISSUE THREAD

**Issue by jd-solanki** [antfu/eslint-config#91]
Hi,

I am using your config by following readme and I extended from `@antfu`. However, When I use TSX in my vue project it is showing eslint errors for react:
![image](https://user-images.githubusercontent.com/47495003/167780031-64e6c776-92d7-49fa-8174-eef19d0097bc.png)

**Comment by antfu** [comment]
Maybe install `@antfu/eslint-config-vue` and extend from it instead?

**Comment by jd-solanki** [comment]
Thanks :)
