### ISSUE TITLE
consult : how config, to format <style> of .vue file

### ISSUE THREAD

**Issue by a982246809** [antfu/eslint-config#96]

**Comment by antfu** [comment]
It does not. Maybe you can use a formatter or and addition eslint plugin to do it.

**Comment by liamwang** [comment]
I'm also looking for a good way to do this. I'm currently using `stylelint` + `stylelint-config-standard` + `postcss` + `postcss-html` + `postcss-less` to format styles in vue file, but it is too much cumbersome. 

If any of you know of a better way, please let me know.

**Comment by ijkml** [comment]
Following... I'm here with the same issue. Might have to use @liamwang 's setup meanwhile.

**Comment by so1ve** [comment]
You can write a small eslint plugin and use prettier to format the style block

**Comment by antfu** [comment]
https://github.com/antfu/eslint-config#how-to-lint-css

**Comment by warmthsea** [comment]
**StyleLint format css、scss、<style> of .vue file**
**Example：**

> **package.json**
> devDependencies

`stylelint`
`postcss`
`postcss-html`
`stylelint-config-standard-scss`
`stylelint-config-recommended-vue`


> **.stylelintrc.json**
```
{
  "extends": ["stylelint-config-standard-scss","stylelint-config-recommended-vue/scss"],
  "rules": {
     "indentation": 2,
     "max-empty-lines": 1,
      ...
   }
}
```

> **./vscode/setting.json**
```
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.fixAll.stylelint": true
  },
"stylelint.validate": ["css", "scss", "sass", "vue"],
...
```

**Comment by antoniogiroz** [comment]
> "stylelint.validate": ["css", "scss", "sass", "vue"],

Does that work for .css files as well? When I add that line, formatting on save for .css files does not work.

This is my config:

```
{
  // Enable the ESlint flat config support
  "eslint.experimental.useFlatConfig": true,

  "css.validate": false,
  "less.validate": false,
  "scss.validate": false,

  // Disable the default formatter, use eslint instead
  "prettier.enable": false,
  "editor.formatOnSave": false,

  // Auto fix
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": "explicit",
    "source.fixAll.stylelint": "explicit",
    "source.organizeImports": "never"
  },

  // Enable eslint for all supported languages
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "vue",
    "html",
    "markdown",
    "json",
    "jsonc",
    "yaml",
    "toml"
  ],

  "stylelint.validate": ["css", "vue"],
}
```

**Comment by csntr** [comment]
I think the solution from @warmthsea no longer works as `indentation` was removed in v15 of stylelint as they said that things like prettier are better for this.

**Comment by datnguyen-tech** [comment]
Hi, has anyone found a solution yet?

**Comment by so1ve** [comment]
> Hi, has anyone found a solution yet?

https://github.com/antfu/eslint-config#formatters

**Comment by datnguyen-tech** [comment]
> > Hi, has anyone found a solution yet?
> 
> https://github.com/antfu/eslint-config#formatters

thanks bro!
