### ISSUE TITLE
eslint不会自动修复单行过长的问题

### ISSUE THREAD

**Issue by linkscope** [antfu/eslint-config#97]
我现在正在习惯仅使用eslint格式化代码，但现在有个不太舒服的点是我限制了单行最大长度，但eslint不会帮我自动折行，Anthony宝贝有没有什么替代方案，爱你~

```json
"rules": {
    "max-len": [
      "error",
      {
        "code": 80
      }
    ]
}
```

**Comment by antfu** [comment]
What's exactly what I dislike about prettier. Feel free to configure it your own.

**Comment by jaycethanks** [comment]
> That's exactly what I dislike about prettier. Feel free to configure it your own.

fufu 桑 ~~, 你是说去配置 prettier 吗？

**Comment by so1ve** [comment]
eslint没办法做这事，你要不然去试试dprint
